### ISSUE TITLE
Support new Redis 6.2 arguments for XSETID

### ISSUE THREAD

**Issue by chayim** [predis/predis#1000]
Add support for the enw arguments in Redis 6.2 for XSETID as specified at https://redis.io/commands/XSETID.

Detail of update: Added the `entries_added` and `max_deleted_entry_id` arguments.

This is part of #820.
Note: Due to the autogenerated nature of this, some of this may be already implemented.

**Comment by vladvildanov** [comment]
Closes as this command is Redis internal
