### ISSUE TITLE
Breaking change in v2.1.0

### ISSUE THREAD

**Issue by driesvints** [predis/predis#1016]
**Describe the bug**
Since v2.1.0 we're experiencing a breaking change when running `zinterstore` and passing an array as weights: https://github.com/laravel/framework/actions/runs/3936474461/jobs/6734736234#step:9:102

Builds of Laravel framework and every PR are now failing. Would appreciate some quick action on this if possible. I wasn't able to determine how to solve this. 

If the below isn't considered appropriate usage then can you point to some docs on how to use this method call?

**To Reproduce**

```php
$redis->zinterstore('output2', ['set1', 'set2'], [
    'weights' => [3, 2],
    'aggregate' => 'sum',
]);
```

**Expected behavior**
Before this worked and no errors showed.

**Versions (please complete the following information):**
 - Predis: [e.g. 2.1.0]
 - PHP [e.g. 8.0.27]
 - Redis Server [e.g. 5.3.7]
 - OS [e.g. Ubuntu 22.04]

**Code sample**
See above.

**Additional context**

**Comment by vladvildanov** [comment]
@tillkruss Will have a look tomorrow morning

**Comment by tillkruss** [comment]
> @tillkruss Will have a look tomorrow morning

That's too late, I fixed it.

**Comment by driesvints** [comment]
That fixed it, thanks @tillkruss
