### ISSUE TITLE
Integrate code coverage scanning

### ISSUE THREAD

**Issue by chayim** [predis/predis#1023]
As part of the ongoing support for versions, etc we'd like to ensure we don't break APIs! One of the ways to do this, in line with other clients is to integrate [codecov](https://codecov.io).

I'll happily do the integration - but we need to connect this to codecov - via their interface as well.

**Comment by tillkruss** [comment]
It's connected 👍

**Comment by tillkruss** [comment]
See #1036.

**Comment by chayim** [comment]
Seeing coveralls integration I think we can close this. Coverage is coverage.
