### ISSUE TITLE
Stream commands (e.g. `xadd`) are not applying the key prefix

### ISSUE THREAD

**Issue by jessarcher** [predis/predis#1050]
**Describe the bug**
Stream commands like `xadd` are not applying the key prefix.

**To Reproduce**
1. Initialize `Predis\Client` with a prefix (e.g. 'sample:').
2. Call the `xadd` method with a key (e.g. 'my-stream-key').
3. List the keys and see that the new key is missing the configured prefix.

**Expected behavior**
The configured key prefix should be prepended to the key provided to `xadd`.

**Versions (please complete the following information):**
- Predis: 2.1.1
- PHP: 8.2.1
- Redis Server: 7.0.5
- OS: Fedora 37

**Code sample**
```php
$client = new \Predis\Client(null, ['prefix' => 'sample:']);

$client->xadd('my-stream-key', ['foo' => 'bar']);

$client->keys('*'); // []

$client->executeRaw(['KEYS', '*']); // ['my-stream-key']

$client->xrange('my-stream-key', '-', '+'); // Returns the stream, indicating that xrange probably ignores the prefix too.
```

**Additional context**
The issue does not exist with other data structures using the same client instance above.

**Comment by vladvildanov** [comment]
@jessarcher Thank you for your report! Just added a PR to fix this issue. Please make sure you're using correct prefix pattern, prefixes with `:` occurs `WRONGTYPE Operation against a key holding the wrong kind of value` redis server error. 

Try this one:

`$client = new \Predis\Client(null, ['prefix' => 'sample-']);

$client->xadd('my-stream-key', ['foo' => 'bar']);

$client->xrange('my-stream-key', '-', '+');`

**Comment by jessarcher** [comment]
Thank you @vladvildanov! :pray: 

Just as a heads up, the `sample:` prefix in my reproduction example comes from this project's readme: https://github.com/predis/predis#client-configuration.

**Comment by vladvildanov** [comment]
@jessarcher Sure, in most cases prefix pattern doesn't matter, but in this it is 👌
