### ISSUE TITLE
How In  laravel 9 make nested inserted objects ?

### ISSUE THREAD

**Issue by sergeynilov** [predis/predis#1154]
In  laravel 9.4 app with predis/predis 2.1 I write data with

  Redis::set('key', serialize( $data ) );

method and in phpRedisAdmin I see that all written data are written on the same level, but I need root object and nested inserted objects.
How can I do it ?

Thank you!

**Comment by tillkruss** [comment]
Ask the phpRedisAdmin team.

**Comment by sergeynilov** [comment]
1) But how in Redis::set('key') can I set parentNode/subnodes ?
2) Can you advice some other tool to see parentNode/subnodes ?
