### ISSUE TITLE
[Help wanted] Bare Redis class disconnecting between DI factory and service

### ISSUE THREAD

**Issue by jrcii** [predis/predis#1194]
I had a weird issue using the `Redis` class directly as provided by the PHP extension, where the connect would drop if the client object was passed between my DI factory and service. I'd have to call `connect()` in the object making the call. Using Predis this issue disappeared.

I'm just curious, does anyone have any insight into what may have been going on here? Thank you.

**Comment by tillkruss** [comment]
That's part of https://github.com/phpredis/phpredis
