### ISSUE TITLE
Add instructions for installing via Dockerfile

### ISSUE THREAD

**Issue by tc-tmmlt** [predis/predis#1264]
Installing predis in a docker build requires a bit of gymnastics with composer:  Composer is tricky, often requiring 2 stages in building [(as here)](https://stackoverflow.com/questions/46786589/running-composer-install-within-a-dockerfile).  It sure would be great to have some code showing how to add predis into a Wordpress docker build -- and even better if you could get the folks at Wordpress to take your code into a PR for their builds.

Absent that, sadly, it is just easier to slip a pecl install for "the other guys" into the Wordpress docker file and call it a day.    Makes me sad to do that, as I want to support predis.   Thanks for considering.

**Comment by tillkruss** [comment]
We accept PRs if you'd like to add an example to `examples/`.
