### ISSUE TITLE
Cannot use 'DEL' with redis-cluster.

### ISSUE THREAD

**Issue by MrMeizi** [predis/predis#1301]
**Describe the bug**

**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**

**Versions (please complete the following information):**
- Predis: [e.g. 2.1.2]
- PHP [e.g. 7.4.33]
- Redis Server [e.g. 6.2.7]
- OS [e.g. centos 7]

**Code sample**
If applicable, a small snippet of code that reproduces the issue.

**Additional context**

Cannot use 'DEL' with redis-cluster.

**Comment by tillkruss** [comment]
Not enough information.
