### ISSUE TITLE
PHP 8.2 deprecation: Use of "static" in callables is deprecated

### ISSUE THREAD

**Issue by nicolas-grekas** [predis/predis#1329]
Both in branches 1.x and 2.x, KeyPrefixProcessor is relying on deprecated callables and triggers this deprecation, as explained in this RFC (there may be other classes affected, I didn't check):
https://wiki.php.net/rfc/deprecate_partially_supported_callables

**Comment by tillkruss** [comment]
@nicolas-grekas Do you have a suggestion on how to avoid deprecated callables?

**Comment by nicolas-grekas** [comment]
For v2.x, this has been fixed in #797
For v1.x I propose #1403
