### ISSUE TITLE
Error on RPOP expects exactly 1 argument, 2 given

### ISSUE THREAD

**Issue by manuirrazabal** [predis/predis#1410]
**Describe the bug**
When I execute the command Rpop I get the following error
```
RPOP expects exactly 1 argument, 2 given
```
When I add the second parameter. (Number of elements)

I also tried ExecuteRaw with the same result. 

I dug into the code and I notice the ClientContextInterface.php rpop is listed it with a single parameter

**Versions (please complete the following information):**
- Predis: [e.g. 1.1.2]
- PHP [e.g. 8.2]

**Comment by tillkruss** [comment]
@vladvildanov: Let's fix this in v2.x, eh?

**Comment by manuirrazabal** [comment]
I will close this issue. I found the reason, redis started to support this new field from the version 6 and I had the version 5 on my server. 

Sorry about the noise
