### ISSUE TITLE
Question: the `ClientInterface::eval` signature and PhpRedis

### ISSUE THREAD

**Issue by a-menshchikov** [predis/predis#1426]
Maybe it's my mistake, but I've thought that the `eval` method signature that provided by the Predis should be compatible with the PhpRedis one. Since #762 it's not and in particular I have Phan errors about this.

Should the method signature be fixed in the ClientInterface annotation, or is it OK and I'm doing something wrong?

**Comment by tillkruss** [comment]
There is no API compatibility between Predis and PhpRedis and likely will never be.
