### ISSUE TITLE
laravel 10 get error every second with "predis/predis": "^2.2"

### ISSUE THREAD

**Issue by Rasoul-Karimi** [predis/predis#1461]
i get every second this log error with predis 2.2

`vendor/composer/../predis/predis/src/Command/ZSetRemove.php): Failed to open stream: No such file or directory vendor/composer/ClassLoader.php:571)`

**Comment by vladvildanov** [comment]
@Rasoul-Karimi Hi! Just tried `"predis/predis": "^2.2"` with pure laravel 10.x and it works. Looks like the problem not related to predis itself

**Comment by Rasoul-Karimi** [comment]
> @Rasoul-Karimi Hi! Just tried `"predis/predis": "^2.2"` with pure laravel 10.x and it works. Looks like the problem not related to predis itself

hi .. use laravel 11

**Comment by vladvildanov** [comment]
@Rasoul-Karimi I guess you're trying to run a non-existing command. Could you please check your code for something like `$client->zsetremove()`

**Comment by vladvildanov** [comment]
@Rasoul-Karimi Predis dynamically resolves a command depends on a method call, so if you're dynamically generating command name (f.e `$client->{$variable}`) make sure that it's a valid command name

**Comment by Rasoul-Karimi** [comment]
> @Rasoul-Karimi I guess you're trying to run a non-existing command. Could you please check your code for something like `$client->zsetremove()`

no this is not my code or used command! this is a old predis command i think

**Comment by Rasoul-Karimi** [comment]
> @Rasoul-Karimi Predis dynamically resolves a command depends on a method call, so if you're dynamically generating command name (f.e `$client->{$variable}`) make sure that it's a valid command name

no is sorry i dont not use dynamically... i just use laravel global redis command like: set , get !

**Comment by Rasoul-Karimi** [comment]
> > @Rasoul-Karimi I guess you're trying to run a non-existing command. Could you please check your code for something like `$client->zsetremove()`
> 
> no this is not my code or used command! this is a old predis command i think

look here:
https://gitlab.raisound.com:9443/wenyi.chen/data-collect-api/blob/1ab962f81cb4d08309c200ba1ba871b5b78babc1/vendor/predis/predis/src/Command/ZSetRemove.php
i think this command exeist before on old version of predis

**Comment by Rasoul-Karimi** [comment]
https://github.com/laravel/framework/issues/42837

**Comment by vladvildanov** [comment]
@Rasoul-Karimi Yeah, it existed before with wrong name, the command you need switch to is `$client->zrem()`

**Comment by Rasoul-Karimi** [comment]
> zrem

i dont use that command ! i think laravel horizon use that

**Comment by vladvildanov** [comment]
@Rasoul-Karimi Ah, I didn't see a whole trace so I thought it's an issue in your application code. Well, I think you should open a bug then cause it looks like they have support for Predis ^2.0

https://github.com/laravel/horizon/blob/5.x/composer.json#L31

**Comment by Rasoul-Karimi** [comment]
> @Rasoul-Karimi Ah, I didn't see a whole trace so I thought it's an issue in your application code. Well, I think you should open a bug then cause it looks like they have support for Predis ^2.0
> 
> https://github.com/laravel/horizon/blob/5.x/composer.json#L31

look:

![image](https://github.com/predis/predis/assets/9654616/9a970eb3-b4cc-41a4-90fb-77ab7656a032)

this is a horizon error of bug

**Comment by vladvildanov** [comment]
@Rasoul-Karimi Got it! Definitely open bug on Horizon part, they have to fix 2.0 compatability

**Comment by 5priyanka** [comment]
I have the above issue with Laravel Framework 9.52.20 and predis v3.0.1 how to reoslved? 

/var/www/html/storage/logs/laravel-2025-06-30.log:[2025-06-30 07:09:28] production.ERROR: include(/var/www/html/vendor/composer/../predis/predis/src/Command/ZSetReverseRangeByScore.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/var/www/html/vendor/composer/../predis/predis/src/Command/ZSetReverseRangeByScore.php): Failed to open stream: No such file or directory at /var/www/html/vendor/composer/ClassLoader.php:571)

2025-06-30 07:11:24] production.ERROR: include(/var/www/html/vendor/composer/../predis/predis/src/Command/ZSetRemove.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/var/www/html/vendor/composer/../predis/predis/src/Command/ZSetRemove.php): Failed to open stream: No such file or directory at /var/www/html/vendor/composer/ClassLoader.php:571)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(272): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, '...', '...', 571)
#1 /var/www/html/vendor/rollbar/rollbar/src/Handlers/ErrorHandler.php(32): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, '...', '...', 571)
#2 /var/www/html/vendor/composer/ClassLoader.php(571): Rollbar\\Handlers\\ErrorHandler->handle(2, '...', '...', 571)
#3 /var/www/html/vendor/composer/ClassLoader.php(571): include('...')
#4 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('...')
#5 /var/www/html/vendor/predis/predis/src/Profile/RedisProfile.php(92): Composer\\Autoload\\ClassLoader->loadClass('...')
#6 /var/www/html/vendor/predis/predis/src/Client.php(323): Predis\\Profile\\RedisProfile->createCommand('...', Array)
#7 /var/www/html/vendor/predis/predis/src/Client.php(314): Predis\\Client->createCommand('...', Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call('...', Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(229): Illuminate\\Redis\\Connections\\Connection->command('...', Array)
#10 /var/www/html/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(154): Illuminate\\Redis\\Connections\\Connection->__call('...', Array)
#11 /var/www/html/vendor/laravel/horizon/src/Supervisor.php(216): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->forget(Array)
#12 /var/www/html/vendor/laravel/horizon/src/Supervisor.php(320): Laravel\\Horizon\\Supervisor->terminate()
#13 /var/www/html/vendor/laravel/horizon/src/Supervisor.php(286): Laravel\\Horizon\\Supervisor->ensureParentIsRunning()
#14 /var/www/html/vendor/laravel/horizon/src/Supervisor.php(260): Laravel\\Horizon\\Supervisor->loop()
#15 /var/www/html/vendor/laravel/horizon/src/Console/SupervisorCommand.php(104): Laravel\\Horizon\\Supervisor->monitor()
#16 /var/www/html/vendor/laravel/horizon/src/Console/SupervisorCommand.php(78): Laravel\\Horizon\\Console\\SupervisorCommand->start(Object(Laravel\\Horizon\\Supervisor))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\SupervisorCommand->handle(Object(Laravel\\Horizon\\SupervisorFactory))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#23 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#25 /var/www/html/vendor/symfony/console/Application.php(1078): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SupervisorCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 {main}
"}
