### ISSUE TITLE
`SET` throws if you pass `null` to flag

### ISSUE THREAD

**Issue by nickdnk** [predis/predis#1463]
**Describe the bug**
You can run this command with Redis:

```
SET foo bar
+OK
SET foo bar XX EX 600 // Only update if already set
+OK
GET foo
$3
bar
TTL foo
:598
```

Which you can also do with predis:

```php
$client->set('foo', 'bar', 'EX', 1800, 'XX');
```

But if you pass `null` to the last argument, it throws `ERR syntax error` error.
```php
$client->set('foo', 'bar', 'EX', 1800, null);
```

Which is really weird, as the default argument to this parameter is `null`:

```php
@method Status set(string $key, $value, $expireResolution = null, $expireTTL = null, $flag = null)
```

And this works, if you simply omit the last parameter:
```php
$client->set('foo', 'bar', 'EX', 1800);
```

What argument do I pass to `$flag` if I don't want any flags? I tried with `false` and an empty string as well, but they all throw. In my case I encountered this when using a ternary, i.e.

```php
$client->set('foo', 'bar', 'EX', 1800, $update ? 'XX' : null);
```

I took a look at the code, and it seems that `XX` and `NX` are sometimes being passed to `expireResolution`, not to `flag`. These are not expiration resolution arguments ([those are `EX`, `PX`, `EXAT`, `PXAT` and arguably `KEEPTTL`](https://redis.io/docs/latest/commands/set/)), so maybe something is wrong in general with this logic?

Examples:
https://github.com/predis/predis/blob/cbef71090b710063cbc3e00b8f29947195846ce9/tests/Predis/Command/Redis/SET_Test.php#L168-L176

https://github.com/predis/predis/blob/cbef71090b710063cbc3e00b8f29947195846ce9/tests/Predis/Command/Redis/SET_Test.php#L146-L152

These should probably use this syntax, which also produces a syntax error on the current version of predis:

```php
public function testSetStringValueWithModifierNX(): void
{
    $redis = $this->getClient();
    $this->assertEquals('OK', $redis->set('foo', 'bar', null, null, 'NX'));
    $this->assertNull($redis->set('foo', 'bar', null, null, 'NX'));
}
```

**Versions (please complete the following information):**
- Predis: 2.2.2
- PHP 8.2.15
- Redis Server 7.0.15
- OS: Linux

**Comment by vladvildanov** [comment]
@nickdnk Thank you fro reaching us out! The PR above should fix the bug
