### ISSUE TITLE
Add comments for what each function does

### ISSUE THREAD

**Issue by brudermusscode** [predis/predis#1469]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when in need of a function, seeing a list of all that are attached to the \Predis\Client and not knowing what each function does.

**Describe the solution you'd like**
A comment for each function, which explains what they do, so any Intellisense would show it when hovering over or preselecting it.

Thank you!

**Comment by tillkruss** [comment]
Use an IDE.
