### ISSUE TITLE
[Wiki Question] Connection Parameters timeout and read_write_timeout

### ISSUE THREAD

**Issue by snmatsui** [predis/predis#1487]
Predis includes the parameters `timeout` and `read_write_timeout`.
https://github.com/predis/predis/wiki/Connection-Parameters

https://github.com/predis/predis/blob/v2.x/src/Connection/StreamConnection.php#L103
The `timeout` parameter is passed to `stream_socket_client`, while `read_write_timeout` is passed to `stream_set_timeout`.

https://www.php.net/manual/en/function.stream-socket-client.php
https://www.php.net/manual/en/function.stream-set-timeout.php
https://www.php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout

The default `timeout` value for `stream_socket_client` is determined by the `default_socket_timeout` setting in `php.ini`, which is typically 60 seconds.

The Wiki Page notes that the default value for `read_write_timeout` is 60 seconds.
However, the more accurate description would be: "The default value for `timeout` is 60 seconds, while `read_write_timeout` does not have a defined default value."

**Comment by tillkruss** [comment]
Thanks for the details. I've update the wiki.
