### ISSUE TITLE
Support for KEYS* command with redis clustering

### ISSUE THREAD

**Issue by integrii** [predis/predis#172]
It would be possible to run a KEYS command on all nodes of a cluster, then combine the results.  This makes it possible to search for a pattern of keys. 

In my app, I want to be able to delete everything for a specific user.  My key path is always username:stuff.

It is nearly a deal breaker to not be able to run KEYS username:\* and then delete everything for a specific user found in the reply.  I would really appreciate this feature!

**Comment by jadbox** [comment]
Any updates on this? How do I iterate on all active cluster nodes if the connections are lazily initialized?

**Comment by JasonLantz** [comment]
bump for the Keys feature...

**Comment by espiegel** [comment]
another bump for this feature

**Comment by ravikanthg1** [comment]
I have a very similar requirement, need to search for pattern with keys in cluster,  how can i do this in java ?  @nrk or anyone..

**Comment by diimpp** [comment]
+1

**Comment by JasonLantz** [comment]
have you guys tried using hgetall?

**Comment by diimpp** [comment]
@JasonLantz how does it suppose to help to get list of keys?

Anyway, @nrk solution in second comment worked for me.
It connected to 3 out 3 nodes, not like it was stated to connect to only first one.

Maybe it was fixed, maybe I've misunderstood and this is a correct behaviour.
I'm calling predis from SncRedis bundle's service.

**Comment by woverton** [comment]
+1

**Comment by ahfeel** [comment]
:+1:

**Comment by nrk** [comment]
See my comments on #338 for a better and updated solution on how to iterate over the master nodes of redis-cluster to perform some commands on each node or iterate the keyspace as a whole in a decently efficient way.

**Comment by kofrezo** [comment]
+1
