### ISSUE TITLE
SET fails when expireResolution is set

### ISSUE THREAD

**Issue by theDisco** [predis/predis#203]
I am using the 1.0.0 version of predis and the current version of redis from ubuntu repositories

```
$ apt-cache policy redis-server
redis-server:
  Installed: 2:2.8.4-2
  Candidate: 2:2.8.4-2
  Version table:
 *** 2:2.8.4-2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/statu
```

when I attempt to set expireResolution, command fails with `-ERR syntax error`. Here is an example code to reproduce:

``` php
$options = [
    'profile' => new \Predis\Profile\RedisVersion280
];
$predis = new \Predis\Client(null, $options);
$predis->set('test', 'test', 1000);
```

It seems that redis do not support additional arguments in SET although I couldn't find the exact protocol specification. I think you should change the method signature in the ClientInterface. I can send you a pull request for that. If you have any other ideas how to fix it (e.g. argument filtering), please share.

Best

**Comment by gabidavila** [comment]
just a correction @nrk,

It should be 

```php
$predis->setex("key", 1000, "value");
```

**Comment by nickpastuhov** [comment]
This project needs a good documentation, better then the existing.

**Comment by COil** [comment]
@nickpastuhov Feel free to submit your PR. :smiley:
