### ISSUE TITLE
fatal error: permission denied, using socket

### ISSUE THREAD

**Issue by 1merlin1** [predis/predis#210]
Hello,
I Can not connect using sockets on predis/ubuntu:
I tried with:
$client = new Predis\Client('unix:///tmp/redis.sock');
$client= new Predis\Client(array('scheme' => 'unix', 'path' => '/tmp/redis.sock'));
in both cases the same error:

Fatal error: Uncaught exception 'Predis\Connection\ConnectionException' with message 'Permission denied [unix:///tmp/redis.sock]' in /usr/share/php/Predis/Connection/AbstractConnection.php:144
Stack trace:
#0 /usr/share/php/Predis/Connection/StreamConnection.php(123): Predis\Connection\AbstractConnection-&gt;onConnectionError('Permission deni...', 13)
#1 /usr/share/php/Predis/Connection/StreamConnection.php(56): Predis\Connection\StreamConnection-&gt;unixStreamInitializer(Object(Predis\Connection\Parameters))
#2 /usr/share/php/Predis/Connection/AbstractConnection.php(93): Predis\Connection\StreamConnection-&gt;createResource()
#3 /usr/share/php/Predis/Connection/StreamConnection.php(134): Predis\Connection\AbstractConnection-&gt;connect()
#4 /usr/share/php/Predis/Connection/AbstractConnection.php(173): Predis\Connection\StreamConnection-&gt;connect()
#5 /usr/share/php/Predis/Connection/StreamConnection.php(160): Predis\Connection\AbstractConnection-&gt;getResource()
#6 /usr/share/php/Predis/Connection/StreamConnection.php(266): Predis\Conn in <b>/usr/share/php/Predis/Connection/AbstractConnection.php </b> on line <b>144</b><br>

any idea how to correct it? 
thank you

**Comment by coin8086** [comment]
@nrk The problem is: the init file placed under /etc/init.d is executed as root so the socket is created and owned by root. So 755 just doesn't work. Either 777 or we can do something to make Redis run the init script as a specified user.
