### ISSUE TITLE
Question about consistent hashing and failover

### ISSUE THREAD

**Issue by omansour** [predis/predis#225]
Hey 

Thanks for predis wich is awesome !

I was wondering if the PredisCluster classes deal with a node lost ? If I cant connect to a server, are the keys redistributed on the other servers ? 

Many thanks

**Comment by nrk** [comment]
No you must remove / replace the unreachable server from the array (that could be done by an external service that rewrites your configurations upon events), and you'd still need to have something taking care of rebalancing your cluster by sharding the keys on the lost node (eg by reading them from the RDB or AOF file) among the surviving nodes, unless you had a slave set up for the lost node.
