### ISSUE TITLE
'shard-01' connection in client-cluster cannot read from 'shard-02'

### ISSUE THREAD

**Issue by decebal** [predis/predis#317]
I kindof inherited this architecture, here is the architecture details:
- 2 web-servers
- each web server has a redis server near it
- redis servers are not setup to shard
- predis has a client-cluster setup
- predis version is 0.8
- predis is used in combination with illuminate/redis

My technical analysis
- the firewalls are not the issue
- 'shard-01' - can read and write to 'shard-02'
- 'shard-01' server has 'shard-02' listed as client
- 'shard-02' - cannot read and write to 'shard-01'
- 'shard-02' server does not have 'shard-01' listed as client

My confusion lies in why is it that the second shard does not list the first one as client.

**Comment by decebal** [comment]
I found so far that I am creating 2 different client side clusters, one from each of my web-servers.
I am trying to avoid using a redis server cluster, so I decided to take my chances with Proxy assisted partitioning and Query routing.

**Comment by nrk** [comment]
@decebal sorry, maybe I'm just missing something but I'm not sure I understand your current setup and what you are actually trying to achieve.

**Comment by decebal** [comment]
@nrk [Old Redis Config](https://sketchboard.me/DzPBvPYskdkU) take a look at the scheme, maybe it helps to spot the same error I did, woould be glad to know your opinion.

**Comment by decebal** [comment]
@nrk 

![My Diagram Image](https://raw.githubusercontent.com/decebal/static/master/new-2-redis-config.png)

 This is the new architecture.

 I am just thinking if there are any caveats that I should be aware of using this one, an obvious one is that I can't use multiple databases with twemproxy.
