### ISSUE TITLE
Error while reading line from the server

### ISSUE THREAD

**Issue by abesto** [predis/predis#32]
`CommunicationException`s are thrown with the message 'Error while reading line from the server' from time to time. The Predis part of an example stack trace:

```
Message: Error while reading line from the server
Thrown at: /var/www/lib/redis/Predis.php:1568
Trace:
#0 /var/www/lib/redis/Predis.php(1636): Predis\Connection->onCommunicationException('Error while rea...')
#1 /var/www/lib/redis/Predis.php(724): Predis\Connection->readLine()
#2 /var/www/lib/redis/Predis.php(1577): Predis\FastResponseReader->read(Object(Predis\Connection))
#3 /var/www/lib/redis/Predis.php(1586): Predis\Connection->readResponse(Object(Predis\Commands\Auth))
#4 /var/www/lib/redis/Predis.php(225): Predis\Connection->executeCommand(Object(Predis\Commands\Auth))
#5 /var/www/lib/redis/RedisProxy.php(21): Predis\Client->__call('auth', Array)
#6 /var/www/lib/redis/RedisProxy.php(21): Predis\Client->auth('password')
```

We couldn't find anything in common in the affected scripts. Some errors are from a local Redis server, some from a remote one. An example that sometimes generates this error:

The script is run by Apache, browsers call it directly by URL, so there can be a lot of instances running at once. The following Redis commands are run via Predis (in this order; `a`, `b` , `c` and `d` are different tables):
- **AUTH**
- SELECT a
- EXISTS
- (if a condition is met) **SETEX**
- SELECT b
- **RPUSH**
- if a condition is met
  - **SELECT b**
  - **INCR**
  - SELECT c
  - **GET**
  - **SELECT d**
  - RPUSH

The bold commands are those that have ever generated the error. The majority (99%) is on AUTH.

**Environment**:

```
$ redis-server -v
Redis server version 2.2.4 (00000000:0)

Predis version 0.6.6

$ php -v
PHP 5.3.3-0.dotdeb.1 with Suhosin-Patch (cli) (built: Oct  1 2010 08:49:29) 
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Xdebug v2.1.0, Copyright (c) 2002-2010, by Derick Rethans

$ /usr/sbin/apache2ctl -v
Server version: Apache/2.2.9 (Debian)
Server built:   Apr 20 2010 15:40:17

```

**Comment by razvanphp** [comment]
Sorry for bringing this up again after so much time, but I think I have a different reason why I get this error message. I tried debugging the stream as mentioned earlier and got this:

```
array(7) {
  ["stream_type"]=>
  string(14) "tcp_socket/ssl"
  ["mode"]=>
  string(2) "r+"
  ["unread_bytes"]=>
  int(0)
  ["seekable"]=>
  bool(false)
  ["timed_out"]=>
  bool(false)
  ["blocked"]=>
  bool(true)
  ["eof"]=>
  bool(false)
}
```

`read_write_timeout` is set to -1, and we use one master and one slave with `replication => true`. Judging by the IP address, the error is triggered on the master.

Any idea about blocking mode connection? I saw [other PHP Redis library](https://github.com/Shumkov/Rediska/blob/master/library/Rediska/Connection.php#L285) has this configurable.

We just switched from phpredis and this is a cron job, the timeout happens exactly after 60 seconds.

Thank you!

**Comment by pravindahal** [comment]
This is how I managed to capture the debug info:

```
          catch (Predis\CommunicationException $exception) {
                $stream = $exception->getConnection()->getResource();
                $errorMessage = var_export(stream_get_meta_data($stream), true);
                //Log::info($errorMessage);
                continue;
            }
```

I get the following:

```
array (
  'timed_out' => false,
  'blocked' => true,
  'eof' => false,
  'stream_type' => 'tcp_socket/ssl',
  'mode' => 'r+',
  'unread_bytes' => 0,
  'seekable' => false,
)
```

I have set read_write_timeout to -1, timeout in redis.conf to 0, second param to blpop as 0. Has anyone managed to find out more about this?

**Comment by bencromwell** [comment]
Hi @pravindahal 

Thanks for posting the debug capturing code. Did you get anywhere towards a resolution? 

I have a similar issue:-

```
array (
  'stream_type' => 'tcp_socket/ssl',
  'mode' => 'r+',
  'unread_bytes' => 0,
  'seekable' => false,
  'timed_out' => false,
  'blocked' => true,
  'eof' => false,
)
```

**Comment by pravindahal** [comment]
No Ben, I haven't been able to resolve this.

Ben Cromwell wrote:

**Comment by bencromwell** [comment]
I find myself back here almost a year later and feel compelled to comment. 

Composer doesn't work (install/update packages) with that socket setting changed.

No idea why the package doesn't seem to respect the configuration settings and is unable to override PHP's default. Leaving this comment here in case anyone is reading this and knows the solution!

**Comment by ZekiJohn** [comment]
> default_socket_timeout

In my case configuring Redis was not enough setting `default_socket_timeout=-1` in php.ini makes it to work.
thanks @bencromwell.
