### ISSUE TITLE
Problem with RedisCluster cluster slots usage

### ISSUE THREAD

**Issue by beberlei** [predis/predis#320]
The RedisCluster connection implementation is faulty, it does not take into account that the random selected node could be in a minority part of a partitioned cluster. If this happens, the map is likely outdated and point reads/writes to a node that does not accept writes anymore, leading to a cluster down error.

Reproduce case:
- Setup at least 2 dedicated nodes with 6 redis instances (3 master, 3 slaves). Split them into 2 master/1 slave and 1 master, 2 slave groups. 
- Make them run as a cluster. 
- Run a load generator (siege, or anything else) on a third node (webserver) that evenly reads and writes into all of the three masters.
- Now force a network partition using iptables between the nodes, leaving the 1 master/2 slave node as the minority partition. Now, connections using the old master of the three 3 nodes in the minority partition will fail, even though the cluster is still up. This is at least 1/6 chance of reads and writes failing. I still have to check what happens if one of the slaves in the minority partition gets selected.

The problem here is PHP being stateless requires to recompute the cluster slots over and over again in every request, so its computationally more expensive than in languages that can keep a global cluster slots map. The only way to mitigate this in a PHP only library is by calling `CLUSTER SLOTS` on more than one node and checking for differences. Correctness can only be achieved by asking all the nodes, so that is too expensive for some use-cases, but maybe clients could configure how many nodes they want to ask to get a picture of the cluster topology.

**Comment by mstaack** [comment]
@beberlei @nrk whats the status here?

**Comment by jorge07** [comment]
Any ideas? I'm very interested in the issue. How can I help?

**Comment by roncemer** [comment]
Is this project now abandoned?  This has been an issue for over a year, rendering predis completely useless in a clustered environment (which is the only reason one would use predis over phpredis).

One would think a show-stopping bug like this would have been fixed by now.

**Comment by mstaack** [comment]
i am using this as a middleman between php and redis cluster
https://github.com/eleme/corvus
