### ISSUE TITLE
Error while reading line from the server

### ISSUE THREAD

**Issue by googleguy** [predis/predis#33]
Using redis for php 5.2 branch. I'm getting random "Error while reading line from the server" error. The command i used is lpush a serialized string. 

I'm using predis on a php daemon script, meaning it's up all the time. I've already set the timeout for redis.conf to 0.

**Comment by szegad** [comment]
Please notice that that the parameter `connection_timeout` has been renamed to `timeout` in the new version of Predis.

**Comment by mityukov** [comment]
I'm using '**h**keys' pretty extensively. Can this lead to locks?

**Comment by aditya-rewari-cb** [comment]
> If you are using Predis in a daemon-like script you should set `read_write_timeout` to `-1` if you want to completely disable the timeout (this value works with older and newer versions of Predis). Also, remember that you must disable the default timeout of Redis by setting `timeout = 0` in [redis.conf](https://github.com/antirez/redis/blob/2.2.10/redis.conf#L38) or Redis will drop the connection of idle clients after 300 seconds of inactivity.

Any drawback or caution associated with setting timeout=0 at redis.conf ?

What I suspect is ..as connections will never drop
Redis utilisation will stay high

**Comment by aditya-rewari-cb** [comment]
> nrk, thank you again for your reply. I found the problem, and it's just the server running out of ip_conntrack issue. Once the conntrack is fixed, the connection timeout goes away as well.

How to fix this contract.. where to look for ?

**Comment by nrk** [comment]
@aditya-rewari-cb actually `timeout = 0` in redis.conf is the default since Redis 2.4 (released a few years ago) so I'd say there are no drawbacks.

**Comment by aditya-rewari-cb** [comment]
> If you are using Predis in a daemon-like script you should set `read_write_timeout` to `-1` if you want to completely disable the timeout (this value works with older and newer versions of Predis). Also, remember that you must disable the default timeout of Redis by setting `timeout = 0` in [redis.conf](https://github.com/antirez/redis/blob/2.2.10/redis.conf#L38) or Redis will drop the connection of idle clients after 300 seconds of inactivity.

I am using Redis with **daemon proceses** (laravel supervisor workers), as well as , with **regular caching**
Any caution for using 'read_write_timeout' => -1 ?
I wanted to confirm for any possibility of breakage or bug.. in my regular caching usage of Redis, owing to this change !

Thanks !

**Comment by jackbaron** [comment]
@aditya-rewari-cb I have a same problem. You found a solution for it?

**Comment by aditya-rewari-cb** [comment]
> @aditya-rewari-cb I have a same problem. You found a solution for it?

I have vague memory of this now!
But, we went ahead with read_write_timeout=0
