### ISSUE TITLE
Load balanced Redis Sentinel

### ISSUE THREAD

**Issue by cooperaj** [predis/predis#370]
In my docker infrastructure I'm running a number of Sentinels. They all sit behind a load balanced service that I can use to contact any running sentinel. The service is load balanced in a round robin fashion so spreads the load nicely. 

I thought I'd take advantage of this by configuring my app to use only one sentinel connection but having done so I found that only one Sentinel server got any load. So I configured predis with 3 identical Sentinel connections and found that it used all three of my servers.

I'll do this for my project but I think it could be a good thing to support.

**Comment by nrk** [comment]
Sorry but I'm not sure I understand how your infrastructure works and what's the role of that "load balanced service" in the actual communication between Predis and the sentinel instances. If you specify just one sentinel server in the client configuration Predis will only use that one sentinel instance to fetch the actual Redis nodes configuration.

**Comment by lulyon** [comment]
@cooperaj I assume I know what you are talking about. If so, this is the recommended solution:
modify Predis\Connection\Aggregate\SentinelReplication.php line 101: 
    protected $updateSentinels = false;
to be:
     protected $updateSentinels = true;
which lead to sentinels update with only a single sentinel as parameter before `getconnection`.

**Comment by cooperaj** [comment]
@nrk My sentinels exist as a containerised 'service' within our infrastructure. I have 3 of them running right now but they live behind a load balancer so that accessing "sentinel:26379" (for example) will get me one of them. But I do not know which.

I was hoping to be able to configure predis with a single sentinel instance and have it pull information from a different one each time (each request will be round robined) but it appears that it instantiates at load time and keeps it so that it only ever looks at a single sentinel instance. 

I've changed our configuration to have 3 identical sentinel servers. Because of the loadbalancer each one will actually end up and a different endpoint. This seems to work ok.

**Comment by nrk** [comment]
@cooperaj did the solution proposed by @lulyon work for you in the end? By the way you can configure the aggregate connection backend to update the sentinel list by using `$client->getConnection()->setUpdateSentinels(true);`

**Comment by cooperaj** [comment]
Ok. I've finally got around to giving this a go (sorry for the delay) and it's given me some success.

I am calling `$client->getConnection()->setUpdateSentinels(true);` as you advised and am finding that yes my sentinel list is updated with a fuller list when it's set. I'm partially there :)

But there's an issue. My initial sentinel is configured using a hostname (in my case "redis-sentinel"). This is resolved using the internal docker resolver to an IP. For arguments sake lets define this as 172.2.0.9.

When update sentinels is called I get two sentinels details returned (out of three running, they don't return themselves). These are returned with IP addresses - not hostnames - and so when added to the array of sentinels I end up with 

 - redis-sentinel
 - 172.2.0.10
 - 172.2.0.11

As you can see the array does not contain the *.9 address and due to the way docker DNS works 'redis_sentinel' can't be relied upon to return it. This isn't a major issue but it does reduce the number of configured sentinels to two (in 2 out of 3 requests) as opposed to the three running.

This shouldn't be a major issue in my short lived web requests but I would like to figure something out for longer lived service workers.

Having looked through the code a bit more in depth I can see that there are some edge cases around line 271 in `SentinelReplication.php`.

1. If you configure it with just a single Sentinel then failure of that Sentinel stops the code from working (array_shift removes it from the list). In the case of a Docker (Swarm, Kubernetes, Mesos) or Amazon ELB hostname that doesn't make any sense since the hostname will be pointing at a new instance before you can blink.
2. Because the sentinel connection is cached, long running code will always use the same Sentinel. It could be worth having a TTL on the connection?

**Comment by nrk** [comment]
@cooperaj I'm leaving tomorrow for a couple of weeks, but I'll try to get my head around this next month.

**Comment by benkelukas** [comment]
Hello @tillkruss 

I have the same setup as the OP:

- Redis deployed in k8s using the https://github.com/spotahome/redis-operator  operator which creates load balancer in front of all of the Sentinels, this load balancer address is then used in Predis config, so there is only single host defined
- Predis connection used in a long running PHP process
 
when one of the load balanced Sentinels fail, the single Sentinel host configured is removed from the list (because of array_shift) in `SentinelReplication.php` on line `277` and the code stops working until I restart my long-running process.

I see that the issue was closed, but it is still happening to me, is there anything I can do to support this use case?

thanks!

**Comment by tillkruss** [comment]
@benkelukas Feel free to open a PR.
