### ISSUE TITLE
Command 'iNCRBY' is not a registered Redis command error

### ISSUE THREAD

**Issue by deepmk** [predis/predis#372]
strtoupper function and different character sets in the problem PREDIS package

sample
`setlocale(LC_ALL, 'tr_TR.utf8', 'tr_TR.utf8', 'tr_TR');`

used in a project that brings problems 

sample
`if (isset($this->commands[$commandID = strtoupper($commandID)])) {
            return $this->commands[$commandID];
        }`

INCRBY = iNCRBY

I solved the problem by using mb_strtoupper instead strtoupper.

**Comment by nrk** [comment]
Apparently the Turkish language just decided to make things weird here! Jokes aside, I would've never guessed such an issue when uppercasing strings with plain latin characters but I've [just read about it](http://blog.yjl.im/2011/08/i-and-i-in-turkish.html) here and well... you learn something new every day :smile: Not sure how to fix this right now but unfortunately `mbstring` is a non-default extension so we can't really rely on it.

**Comment by baskan** [comment]
@widlturk  fix is actually just replace ReplaceProfile.php line 85 to:
>         $commandID = mb_strtoupper($commandID, 'UTF-8');

@nrk is there a way that we can use our own Profiler implementing ProfileInterface ?

**Comment by egurelli** [comment]
So same issue happened to me also when I using Laravel (5.3) Cache. I have investigated the issue and codes both Laravel lib and Predis lib.

Looks like Predis proxy commands to Redis. From Laravel (5.3) documents :

> You may interact with Redis by calling various methods on the Redis facade. The Redis facade supports dynamic methods, meaning you may call any Redis command on the facade and the command will be passed directly to Redis.

So my solution on Laravel (probably will be same on other framework platforms or native users) :

use commands like in [Redis documents](http://redis.io/commands/) with "**case sensitive**"

`Redis::incrby`
Result : Command 'iNCRBY' is not a registered Redis command.

`Redis::INCRBY`
Result : Success

Note : Packages/Vendors using "lowercase" Redis commands and that cause same problem : Probably extending Class and redefine functions/methods may solve the issue.

**Comment by nrk** [comment]
@baskan yes with Predis v1.x you can implement [Predis\Profile\ProfileInterface](https://github.com/nrk/predis/blob/v1.1/src/Profile/ProfileInterface.php), extend [Predis\Profile\RedisProfile](https://github.com/nrk/predis/blob/v1.1/src/Profile/RedisProfile.php) or extend one of its subclasses and then pass the instance of this class to the `profile` client option when creating a new client:

```php
$profile = new \My\New\RedisProfile();
$client = new \Predis\Client($parameters, ['profile' => $profile]);
```

Please note that in this specific case you are still going to have problems with other parts of the library where `strtoupper()` is being used for commands, such as [Predis\Command\Processor\KeyPrefixProcessor](https://github.com/nrk/predis/blob/v1.1/src/Command/Processor/KeyPrefixProcessor.php), [Predis\Cluster\ClusterStrategy](https://github.com/nrk/predis/blob/v1.1/src/Cluster/ClusterStrategy.php) and [Predis\Replication\ReplicationStrategy](https://github.com/nrk/predis/blob/v1.1/src/Replication/ReplicationStrategy.php).

**Comment by canturkm** [comment]
If you don't want to change code, 

`export LANG=en_US.utf8`

shell command also solves the problem.

**Comment by MichaelMenge** [comment]
how about setting the locale to "C" or "en_US.utf8" and restoring it to the original before returning to the caller
