### ISSUE TITLE
Rename & Scan in Redis Cluster - with Redis Cluster Hash Tags

### ISSUE THREAD

**Issue by matan-ybrant** [predis/predis#374]
Hi,

I'm trying to rename a key in Redis Cluster, but I'm receiving the following error:

> Fatal error: Uncaught exception 'Predis\NotSupportedException' with message 'Cannot use 'RENAME' with redis-cluster.' in Connection\Aggregate\RedisCluster.php:299

I get the same error for Scan.

When using Redis cluster hash tags, the slot can be calculated according to it - for example, rename "{zone1:subzone1}:mydoc:1" to "{zone1:subzone1}:mydoc:2"

Is there an implementation or plan to support in predis?
If not, would you be willing to receive a PR I'll write adding support for it?

Thanks!

**Comment by nrk** [comment]
It makes perfect sense for both `RENAME` and `SCAN` :+1:, actually it's just an oversight on my part :sweat_smile: If you are still willing to push a couple of separate PRs for both commands against the v1.1 branch for it I'd be great!

**Comment by nickdnk** [comment]
I just ran into this problem with SCAN. Any solution?

**Comment by zeshan77** [comment]
I am facing the same problem with SCAN. Has anybody found a solution?

**Comment by nickdnk** [comment]
@zeshan77 I think this library may have gone stale. I switched to using cheprasov/php-redis-client which works very well and supports the methods you want :)

**Comment by jetmirhaxhisefa** [comment]
> I am facing the same problem with SCAN. Has anybody found a solution?
I did it like this: 
```
$clusterClient = $redis->getClientFor($connectionID)
$clusterClient->scan(0);
```
