### ISSUE TITLE
Redis Cluster + SSL = certificate match error

### ISSUE THREAD

**Issue by nickcv-ln** [predis/predis#384]
If you try to use Redis Cluster with auto discoverability REDIS returns the IP and the port of the shard containing the key.

When the client tries then to connect to the other shard the certificate check will fail because it does not match the IP

```
[ErrorException]
  stream_socket_enable_crypto(): Peer certificate CN=`*.redis.cache.windows.net' did not match expected CN=`XX.XX.XXX.XX'
```

Inside Azure every shard is on the same IP/domain name but using different ports.

One way to solve this issue would be to allow the override of the `host` parameter when creating the connection:

``` php
        if ($this->defaults) {
            $parameters += $this->defaults;
            if (isset($this->defaults['host'])) {
                $parameters['host'] = $this->defaults['host'];
            }
        }
```

If you like the solution I'm happy to create a PR for it.

**Comment by nrk** [comment]
Didn't know how Azure works with Redis in this case but it makes sense, I'm just not sure about the solution so let me think about it.

PS: I won't suggest to set `verify_peer` and `verify_peer_name` to `false` because it's bad 😃
