### ISSUE TITLE
''..' is not a registered Redis command

### ISSUE THREAD

**Issue by 2ge** [predis/predis#40]
Hi,

this works:

$cmdSet = clsRedis::getRedis()->createCommand('set', array('library', 'predis'));
echo $info = clsRedis::getRedis()->executeCommand($cmdSet);

this doesnt:

$cmdSet = clsRedis::getRedis()->createCommand('debug object', array('library'));
$info = clsRedis::getRedis()->executeCommand($cmdSet);

$cmdSet = clsRedis::getRedis()->createCommand('config get', array('*'));
$info = clsRedis::getRedis()->executeCommand($cmdSet);

What I am doing wrong ?

**Comment by cargopilot** [comment]
Using predis v1.0.3. 

I am trying to connect to sentinels. The following works:
$cmd = $sentinel->createCommand("sentinel",                                                 
                                array("get-master-addr-by-name", "mymaster"));                          
$reply = $sentinel->executeCommand($cmd);

This doesn't:
 $cmd = $redisClient->createCommand("role");                               
 $reply = $redisClient->executeCommand($cmd); 
I get "Command 'ROLE' is not a registered Redis command"
