### ISSUE TITLE
Persistent connection identifier broken in 7.0.18RC1

### ISSUE THREAD

**Issue by dominics** [predis/predis#426]
Just an advisory that if you're using 7.0.18RC1 (released March 31), and you're using the `persistent => true`/`?persistent=true` connection parameter, and you've deduped your streams using the path, then you might run into [this PHP issue](https://bugs.php.net/bug.php?id=74429) where the uniqueness of a stream transport URL's path, previously accidentally included as a deduplicating factor in stream URLs when creating persistent connections, now will cause an error. (That it ever worked is an undocumented feature. Sorry :()

The BC break [has been reverted](https://github.com/php/php-src/commit/bf3e2dce) for 7.0.18RCn+1 and the latest 7.1 branch, etc. Which is great. It means you can probably safely upgrade to the latest versions without worrying.

But it remains for the internals team to hash out the details of what official API might be provided to deduplicate persistent streams with the same host/port (and a potentially different Redis DB number context). It could quite conceivably be implemented as a stream context option, and using the path is likely to be deprecated.

We should anticipate needing to:
  - implement support for the new stream option, and
  - possibly retain BC for the connection path if needed (by translating it to the stream option?), until the next major version when we can give it a proper option

Either way, just opening this to track the internals discussions and follow whatever outcome they decide.

**Comment by nrk** [comment]
Thanks @dominics! I was meaning to create an issue for this the other day but you beat me to it :+1: 

This breaking change on PHP's part was introduced by a commit that addressed a [security hole in `fsockopen()`](https://bugs.php.net/bug.php?id=74216) and while they indeed pushed it only for PHP 7.0 and later, Debian backported the fix (along with the BC) to older releases covered by their security maintenance window. As far as I know the affected packages are `5.4.45-0+deb7u8` in Wheezy and `5.6.30+dfsg-0+deb8u1` in Jessie.

**Comment by kiwi129** [comment]
could we use pfsockopen instead when opening er persistent connection? something like this
            $resource = pfsockopen ( $parameters->host ,$parameters->port ,$errno, $errstr ,$timeout );
