### ISSUE TITLE
Transparent compression of stored values

### ISSUE THREAD

**Issue by b1rdex** [predis/predis#444]
I needed to automatically compress values being passed to predis to reduce network utilization.
Searched google a lot, but found nothing to plug in and use.

So today I wrote predis plugin with this functionality and I'm here to present it to you: https://github.com/b1rdex/predis-compressible

I implemented it for `SET` and `GET` for now (to cover my use case).
Please review/test and I'm open for comments and requests for changes.

ps: predis internal architecture seems complicated, but it's really good once I figured out internal data flow. 
One thing that dissapointed me — `Processor` can't affect `command`'s `parseResponse`, only arguments of command. Maybe it would be better to add `setResponse`, `setRawResponse`, `filterResponse` and `getResponse` to `Command` instead of just `parseResponse`.
Imagine you need to add compression + some HMAC or any other plugin that affects response and here is problem. There is `ProcessorChain`, but it only can change arguments, not responses.
Because of this you can't use more than one plugin that changes responses parsing because you need to redefine `parseResponse`.
Another option I can suggest is adding events system to be able to change input/output at any step of execution, but this would require even bigger architecture changes.

**Comment by nrk** [comment]
@b1rdex just to let you know that you comment actually gave me quite a bunch of vague ideas to experiment with in this respect for the next v2.0 in which we already have quite a lot of changes anyway.

An event system would probably be overkill though. All in all the architecture of Predis is a balance of convenience, extensibility and run-time performances (it's still a pure-PHP client implementation so we can't just add too much stuff) so compromises have always played a big part in the internal design of this library.

**Comment by b1rdex** [comment]
Ok man, glad to know you saw this.

8 окт. 2017 г. 18:19 пользователь "Daniele Alessandri" <
notifications@github.com> написал:
