### ISSUE TITLE
Add redis 4.0 profile

### ISSUE THREAD

**Issue by skliarie** [predis/predis#453]
The latest profile in predis-1.1.1 is for redis 3.2.0.

Please add profile for redis 4.0.

**Comment by juneszh** [comment]
the same hope

**Comment by leandrocostam** [comment]
Same here.

**Comment by zuohuadong** [comment]
Same here.

**Comment by tristanbailey** [comment]
Just evaluating redis 4.0.2, is there a change needed to support it in this package?

**Comment by nrk** [comment]
Redis 4.0 doesn't ship with relevant changes or new additions to its commands API so there's no pressing need for a dedicated profile (e.g. the new variadic nature of `HSET` in Redis 4.0 will already work with Predis, while new commands such as `UNLINK` will indeed require to use `Predis\Client::executeRaw()` but you can just inject your own implementation in the profile to overcome this).

Obviously pull requests (with proper tests) are still welcome if anyone really needs a new dedicated profile for Redis 4.0 shipped with Predis ASAP.

**Comment by JindrichPilar** [comment]
> Redis 4.0 will already work with Predis

Is Redis 4.0 "officially" supported? README doesn't mention 4.0 at all.

> Support for different versions of Redis (from 2.0 to 3.2) using profiles.

**Comment by sn01615** [comment]
Same here.

**Comment by tillkruss** [comment]
@skliarie: Can you submit a PR?
