### ISSUE TITLE
[documentation] add "How Predis abstracts Redis commands" to "README.md"

### ISSUE THREAD

**Issue by bruno-ds** [predis/predis#465]
Hello,

your project is great, 
as a beginner user I searched a lot of time how to call redis commands, I think that the section `How Predis abstracts Redis commands` in the [FAQ](https://github.com/nrk/predis/blob/master/FAQ.md#how-predis-abstracts-redis-commands) is really important and should be added to the `README.md`

While this section is greatly writed, I think that an example would be nice, like 
`$client->set("key", "value", "ex", 1000);` is equivalent to native `SET key "value" EX 1000`

**Comment by 0x13a** [comment]
yes this is quite confusing, would be great to have a proper API doc: https://github.com/nrk/predis/issues/484
