### ISSUE TITLE
SORT with read-only slave

### ISSUE THREAD

**Issue by buffcode** [predis/predis#468]
Affects: v1.1.1
Redis Version: 3.2.8

According to https://github.com/antirez/redis/blob/4.0/src/server.c#L252 the `SORT` command is a write command (even without `STORE`), also in 3.x.

I'm currently running into `Predis\Response\ServerException - #0: READONLY You can't write against a read only slave.` with following code using no STORE at all:
```php
$redis->sort(
  'somekey',
  [
    'by' => 'NOSORT',
    'get' => [
      '#',
      'somekey:*->event',
      'somekey:*->location'
    ]
  ]
);
```

**Comment by nrk** [comment]
Fix will be available in Predis v1.1.4. Thank you.
