### ISSUE TITLE
Very slow setting string that's greater than 8 KB

### ISSUE THREAD

**Issue by swvjeff** [predis/predis#469]
I'm experiencing a very slow set/setex response when trying to save a string that is 8 KB or larger. It sounds exactly like the issue posted here: https://github.com/nrk/predis/issues/10, but I haven't found a way around the problem yet.

I've tested this on two machines and see the same results on both. I'm running Predis 1.1.1 and connecting to redis on PHP 7.1.9. One machine connects to a local redis server and the other connects remotely. Both experience the slowdown. Here's the output from a quick benchmark I ran calling `$client->set('key', $string)` 50 times with various string lengths:

```
6743 chars saved. Took 0.0010440349578857 seconds for 50 iterations using phpredis.
6743 chars saved. Took 0.013756990432739 seconds for 50 iterations using Predis.
=========
8033 chars saved. Took 0.00099396705627441 seconds for 50 iterations using phpredis.
8033 chars saved. Took 0.0020210742950439 seconds for 50 iterations using Predis.
=========
8387 chars saved. Took 0.0017600059509277 seconds for 50 iterations using phpredis.
8387 chars saved. Took 1.9728450775146 seconds for 50 iterations using Predis.
```

Any advice on getting around this issue? I'd like to continue using Predis over phpredis, but obviously these benchmarks make it pretty unusable. Thanks!

**Comment by terrylinooo** [comment]
Do you find any solution to resolve this issue? I have the same problem.

**Comment by swvjeff** [comment]
Switch to phpredis

**Comment by itbdw** [comment]
but phpredis is bugy
