### ISSUE TITLE
Setting predis database parameter not working?

### ISSUE THREAD

**Issue by geocine** [predis/predis#48]
I have this as a setting.

```
$single_server = array(
    'host'     => '127.0.0.1',
    'port'     => 6379,
    'database' => 15
);

$remote_single_server = array(
    'host'     => '10.241.54.128',
    'port'     => 6379,
    'database' => 15
);
```

then when I call predis using the following code:
`$r = new Predis\Client($single_server);`

whenever I push a value to the key value store it pushes it to `database 0`
so i have to this then it works.

`$r->select($single_server['database']);`

However when I do this on a  remote client.

```
$r = new Predis\Client($remote_single_server);
$r->select($remote_single_server['database']);
```

It pushes to `database 0`. even though I already specified to `select 15`

What seems to be the problem here? Thanks

accidentally hit the **close issue** button

**Comment by inayir** [comment]
If you add a geometry, use this command:
$redis->geoadd('channel', $lon,$lat,'ticket');
