### ISSUE TITLE
Unable to connect to TLS Elasticcache cluster without specifying all nodes in cluster

### ISSUE THREAD

**Issue by dfontenot** [predis/predis#480]
Hello,

I am having issues using Predis to connect to an Elasticcache cluster, unless I specify all nodes in the cluster in this way:

```
$cluster = [
'tls://tls-cluster-node-001:6379',
'tls://tls-cluster-node-002:6379',
'tls://tls-cluster-node-003:6379'
];
$client = new \Predis\Client($cluster, ['scheme' => 'tls', 'cluster' => 'redis']
```

If I list the cluster configuration endpoint from AWS (using tls URI scheme) as the only endpoint, I get the following error:

```
PHP Fatal error:  Uncaught exception 'Predis\ClientException' with message 'No connections available in the pool' in /opt/php/php-5.6.8/share/pear/Predis/Connection/Aggregate/RedisCluster.php:337
```

Additionally, if I only list one node in the cluster (with the tls URI scheme), Predis will attempt to connect to the other nodes it discovers using the tcp URI scheme (which causes it to fail):

```
PHP Fatal error:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'Error while reading line from the server. [tcp://<node-instance>.cache.amazonaws.com:6379]' in /opt/php/php-5.6.8/share/pear/Predis/Connection/AbstractConnection.php:155
```

Ideally, I would not like to deal with individual nodes and would rather put a DNS entry over the cluster configuration endpoint and only specify that to Predis. This seems like a bug. If it's not, would someone be able to advise me on what is wrong with the setup? Thanks.

Here's my info:

- php version: 5.6.8
- Elasticcache redis driver version: 3.2.6
- Predis version: 1.1.1
- OS: ubuntu 14.04

**Comment by centerorbit** [comment]
I had a similar issue in configuring this.

If you look carefully at the 'Error while reading line from the server', you'll notice that it fell back to `tcp`. This happened when the node sent a `-MOVE` (redirect) back to your client.

The solution is to your issue can be accomplished by specifying 'parameters' in your `options` that are passed in. Parameters set the 'defaults' for the Connection Factory, which is then used when one cluster node informs you to redirect to another node.

I'm using Laravel with Redis, but this configuration is passed through straight to Predis, and it should work for you with minor changes:

        [
            'parameters' => [ // Parameters provide defaults for the Connection Factory
                'password' => env('REDIS_PASSWORD', null), // Redirects needs PW for the other nodes
                'scheme'   => env('REDIS_SCHEME', 'tcp'),  // Redirects also must match scheme
            ],
            'ssl'    => ['verify_peer' => false], // Since we dont have TLS cert to verify
        ]

Also note that it will roll through the various connections, so perform tests at least twice to prove against false positives (hitting the correct cluster node on luck, and not experiencing a redirect).

**Comment by centerorbit** [comment]
@joshymatheww,

I have the `config\database.php` configured to dynamically setup the proper config for redis (cluster or not). Instead of the first line in that file be a `return`, it's now `$database = [`. This is then `array_merge`d with the following dynamic config:

```
$redis = [
    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'client' => 'predis',
    'cluster' => env('REDIS_CLUSTER', false),

    //'default' => [
    //    ...
    //],

    // OR

    //'clusters' => [
    //    'default' => [
    //        ...
    //    ],
    //],


    'options' => [
        'parameters' => [ // Parameters provide defaults for the Connection Factory
            'password' => env('REDIS_PASSWORD', null), // Redirects need PW for the other nodes
            'scheme'   => env('REDIS_SCHEME', 'tcp'),  // Redirects also must match scheme
        ],
        'ssl'    => ['verify_peer' => false], // Since we dont have TLS cert to verify
    ]
    
];

/**
 * Dynamic Redis Cluster Configuration
 *  "But, why??" you might ask yourself.
 *
 *  Because for single-node redis instances the 'default' is top-level to the 'redis' array
 *  That works fine and all, but to use a cluster you need to put the connection details under
 *  a 'clusters' array instead. If you have both single and cluster config at the same time,
 *  the system will see the single-node config first and assume you're just running single-node.
 *  So the two config mechanisms are incompatible to exist at the same time.
 *
 *  Also, the Redis Flush (which is necessary for clusters because cache:clear isn't supported)
 *  does not work for single-node instances (where cache:clear does work).
 *  So, if you check the redis:flush command, you'll see it falls-back to single-node cache:clear
 *  for instances of non-cluster.
 */
if( env('REDIS_CLUSTER', false) ){
    // Config used for clustered setups.
    $redis['clusters']  =
    [
        'default' => [
            [
                'scheme'   => env('REDIS_SCHEME', 'tcp'),
                'host'     => env('REDIS_HOST', 'localhost'),
                'password' => env('REDIS_PASSWORD', null),
                'port'     => env('REDIS_PORT', 6379),
                'database' => env('REDIS_DATABASE', 0),
            ],
        ],
        'options' => [ // Clustering specific options
            'cluster' => 'redis', // This tells Redis Client lib to follow redirects (from cluster)
        ]
    ];

} else {
    // Used for non-cluster setups.
    $redis['default'] = [
        'scheme'   => env('REDIS_SCHEME', 'tcp'),
        'host'     => env('REDIS_HOST', 'localhost'),
        'password' => env('REDIS_PASSWORD', null),
        'port'     => env('REDIS_PORT', 6379),
        'database' => env('REDIS_DATABASE', 0),
    ];
}


return array_merge($database, ['redis' => $redis]);
```

**Comment by joshymatheww** [comment]
@centerorbit  Thank you for the configuration. Here I am facing a problem. I have set the configurations and the Cache values are storing in my local redis server  not in amazon.

**Comment by centerorbit** [comment]
@joshymatheww 
Did you notice how much of my configuration file specifies `env()`, which looks for matches in your `.env` file (https://laravel.com/docs/5.6/configuration#environment-configuration). If you don't specify values in that file, it will "fallback" to using the local redis; because things are pointing to `localhost`.
https://laravel.com/docs/5.6/redis#predis

Also, the last I checked, you cannot access AWS Redis from outside of a VPC without special setup. See:

**Comment by amitsharma334** [comment]
I am facing the same issue. I have added all the required configurations in env file.

**Comment by abbood** [comment]
hi @centerorbit, I just saw your answer above and i was heart broken. So are do you really mean this?

    So the two config mechanisms are incompatible to exist at the same time.

look at the situation i'm facing here: https://stackoverflow.com/questions/57722659/how-to-have-both-clustered-and-non-clustered-redis-connections-in-laravel

**Comment by centerorbit** [comment]
@abbood, to clarify what I mean in the comment is that the default Laravel configuration file setup is not capable to have both cluster and single-node setups at the same time, and then be able to switch between them by changing an env.

In the code example that I provided (where you found that comment), you'll notice I changed the structure of the config file, and now it performs some logic (the if-statement) to determine if it should give the cluster, or single-node instance. This configuration example can have both setups within the same file and you can toggle between them with an env flag.

Looking at your question on StackOverflow, this will only get you half-way there. I have not dynamically changed Redis dbs in the same app, but I'm sure it's possible. (I'll comment more specifically over there)

**Comment by abbood** [comment]
Hey @centerorbit (not sure if you're the N.B. [commenter](https://stackoverflow.com/questions/57722659/how-to-have-both-clustered-and-non-clustered-redis-connections-in-laravel#comment101886125_57722659) on my question) but anyways here is an update on what I'm trying. 

So I'm simply trying to have my cache connection work on a clustered redis connection, and my websocket connection to work on a non-clustered connection, in gherkin:


    Feature: Redis connection changes basd on use
    As a developer 
    I should be able to use different connections (clustered and not clustered) depending on if it's cache, queue/job, or websockets

    Scenario: Cache should use a clustered connection
        # note: to understand what hashslots mean, see
        # https://redis.io/topics/cluster-tutorial#creating-and-using-a-redis-cluster
        Given I want to store keys with different hashslots in cache 
        Then the keys should be saved in different nodes 

    Scenario: Publisher (sockets) should use a non clustered connection
        Given I want to publish an event
        Then this operation should happen in a non clustered connection

the unit test code:


```
class RedisFeatureContext extends FeatureContext
{

    /** @BeforeScenario */
    public function before(BeforeScenarioScope $scope)
    {
        parent::setUp();
    }

    /**
     * @Given I want to store keys with different hashslots in cache
     */
    public function iWantToStoreKeysWithDifferentHashslotsInCache()
    {
        Cache::put('foo', 'bar',1);
        Cache::put('hello', 'world',1);
    }

    /**
     * @Then the keys should be saved in different nodes
     */
    public function theKeysShouldBeSavedInDifferentNodes()
    {
        # note: to understand this example, see 
        # https://redis.io/topics/cluster-tutorial#playing-with-the-cluster
        $bar = Cache::get('foo');
        $this->assertEquals($bar,'bar');

        $world = Cache::get('hello');
        $this->assertEquals($world,'world');
    }

    /**
     * @Given I want to publish an event
     */
    public function iWantToPublishAnEvent()
    {
       // event(new TestEvent()); 
        throw new PendingException();
    }

    /**
     * @Then this operation should happen in a non clustered connection
     */
    public function thisOperationShouldHappenInANonClusteredConnection()
    {
        throw new PendingException();
    }
}
```

I ran this test with the following configurations:

in **Cache.php**

        'redis' => [
            'driver' => 'redis',
            'connection' => 'clustered',
        ],

In **database.php** I was inspired by this [answer](https://stackoverflow.com/a/45354052/766570) and simply put different connections under the redis key: (ie `database.redis.connection-1, database.redis.connection-2 etc)

    'redis' => [
        'clustered' => [
            'client' => 'predis',
            'cluster' => true,
            'options' => [
                'cluster' => 'redis',
                'parameters' => [
                    'host' => env('REDIS_SHARD_1_HOST', '127.0.01'),
                    'password' => env('REDIS_PASSWORD', null),
                    'port' => env('REDIS_SHARD_1_PORT', 6379),
                    'database' => 0,
                    ],
                ],
            'clusters' => [
                'default' => [
                    'host' => env('REDIS_SHARD_1_HOST', '127.0.01'),
                    'password' => env('REDIS_PASSWORD', null),
                    'port' => env('REDIS_SHARD_1_PORT', 6379),
                    'database' => 0,
                ],
                'shard2' => [
                    'host' => env('REDIS_SHARD_2_HOST', '127.0.01'),
                    'password' => env('REDIS_PASSWORD', null),
                    'port' => env('REDIS_SHARD_2_PORT', 6379),
                    'database' => 0,
                ],
                'shard3' => [
                    'host' => env('REDIS_SHARD_3_HOST', '127.0.01'),
                    'password' => env('REDIS_PASSWORD', null),
                    'port' => env('REDIS_SHARD_3_PORT', 6379),
                    'database' => 0,
                ],
                'options' => [
                    'cluster' => 'redis'
                ]
            ],
        ], // end clustered

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => 6379,
            'database' => 0,
            'cluster' => false,
        ],
    ]

but when I run the above test, I get this error

> Predis\Response\ServerException: MOVED 5478 127.0.0.1:7001 in vendor/predis/predis/src/Client.php:370

To simplify things, I ran the following tinker

```
$ php artisan --env=testing tinker
Psy Shell v0.9.9 (PHP 7.1.23 — cli) by Justin Hileman
>>> use Illuminate\Support\Facades\Cache;
>>> Cache::put('foo','bar',1);
Predis/Response/ServerException with message 'MOVED 7837 127.0.0.1:7001'
```
The move error is a known one, it's simply [saying](https://stackoverflow.com/a/53000256/766570) that i'm dealing with a non-clustered redis connection.

What confuses me is if I put a breakpoint in the code here
```  3 vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(108): Illuminate\Redis\Connections\Connection->command('get', Array)```
the connection name _is clustered_.. yet it's treating it as non clustered. 

Any thoughts?

**Comment by abbood** [comment]
@centerorbit i think i just found out what you're talking about here:

>  .. for single-node redis instances the 'default' is top-level to the 'redis' array
>  *  That works fine and all, but to use a cluster you need to put the connection details under
>  *  a 'clusters' array instead. If you have both single and cluster config at the same time,
>  *  the system will see the single-node config first and assume you're just running single-node.
>  *  So the two config mechanisms are incompatible to exist at the same time.

it's basically [this](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Redis/RedisManager.php#L91-L116) guy:

```
/**
     * Resolve the given connection by name.
     *
     * @param  string|null  $name
     * @return \Illuminate\Redis\Connections\Connection
     *
     * @throws \InvalidArgumentException
     */
    public function resolve($name = null)
    {
        $name = $name ?: 'default';
        $options = $this->config['options'] ?? [];
        if (isset($this->config[$name])) {
            return $this->connector()->connect(
                $this->parseConnectionConfiguration($this->config[$name]),
                $options
            );
        }
        if (isset($this->config['clusters'][$name])) {
            return $this->resolveCluster($name);
        }
        throw new InvalidArgumentException("Redis connection [{$name}] not configured.");
    }
```

It's basically treating the `default` connection as mutually exclusive with the `cluster` one.. I'm gonna have to write some code to adjust this. I'll send you a PR just for fun :)

**Comment by centerorbit** [comment]
@abbood, just to clarify from your earlier comment:

> The move error is a known one, it's simply saying that i'm dealing with a non-clustered redis connection.

Take a look at this redis documentation: https://redis.io/topics/cluster-spec

The MOVED error is coming from a Redis node that _is in_ a cluster. That node is essentially saying "I don't have the answer, but go to this other address, because another node in the cluster does know". You should not get a "MOVED" error response from a single-node Redis instance.

**Comment by abbood** [comment]
@centerorbit I created a pull request (but on a fork of the laravel for my company) here:
https://github.com/totersapp/framework/pull/1/commits/714666fb5022c249a93754033f3c29704ee6263c

it's working well for me now! I'll work on a PR for laravel itself soon

**Comment by abbood** [comment]
@centerorbit now I got a problem with specifying redis replication (together with clustering):

https://github.com/nrk/predis/issues/579

**Comment by nrk** [comment]
The second post already answered the original poster question, the rest seems completely unrelated so I'm closing this issue.

**Comment by warrenca** [comment]
Hi @dfontenot,

I just stumbled across this problem and I'm not using any framework. I'm using Predis v1.1.3 and my setup is an AWS Elasticache Redis cluster mode on with TLS and authentication. My connection code is below

```
$queryArray = [
    'password' => $redisPassword,
    'ssl' => [
        'peer_name' => $configEndpoint,
        'verify_peer' => 1,
    ],
];

$query = http_build_query($queryArray);
$dbIndex = 0;

$configEndpointWithParams = sprintf('%s/%d?%s', $dsn, $dbIndex, $query);

$options = [
    'cluster' => 'redis',
    'scheme' => 'tls',
    // global parameters that will be used by clients when there's a node redirection
    // https://github.com/predis/predis/blame/main/README.md#L243
    'parameters' => array_merge(
        $queryArray,
        [
            'database' => $dbIndex,
            'scheme' => 'tls',
        ]
    ),
];

// Just making this obvious that it should be in an array.
$connectionParamatersArray = [$configEndpointWithParams];

$client = new PredisClient($connectionParamatersArray, $options);
```

**Comment by dfontenot** [comment]
@warrenca what I ended up doing was modifying the code in a forked version of predis. I was never able to get mainline predis to work for our use case. However, I have not tried any new versions of predis. Which version are you using?

**Comment by warrenca** [comment]
@dfontenot I'm using Predis v1.1.3 and AWS Redis v6 cluster mode on, with encryption at rest (this could be the AUTH) and with encryption in transit (this could be the TLS/SSL).

Looking at Predis v1.1.1 https://github.com/predis/predis/blob/v1.1.1/README.md, which you said you are using from your original question. Global `parameters` feature is available, which is exactly what I'm using.

**Comment by dfontenot** [comment]
Ok. If I find some time I may be able to rebase my chances on top of the latest version and submit it as a merge request.

**Comment by xavierrigau** [comment]
> 'options' => [ // Clustering specific options
>             'cluster' => 'redis', // This tells Redis Client lib to follow redirects (from cluster)
>         ]

The options solved my issue. 🙇‍♂️
