### ISSUE TITLE
Cannot use TTL on key of hash with redis-cluster

### ISSUE THREAD

**Issue by steve75918** [predis/predis#510]
`$clinet->ttl($key)`
Worked fine on simple key-value, crashed when key is a hash.
Throw exception with message
> Cannot use 'TTL' with redis-cluster

Confirmed both data set do exist in redis-cluster via redis-cli, and response `TTL` command correctly.
Appreciate if anyone can explain why and tell me how to resolve it.

**Snippet Code Simple:**
`$clinet->set($key, $value, 'EX', 3600);`

**Snippet Code Hash:**
`$clinet->hset($key, $name1, $value1);`
`$clinet->hset($key, $name2, $value2);`
`$clinet->expire($key, 3600);`

**Env:**
- Predis: ^1.1
- redis: 3.0.6
- php:  7.2.3
- OS: Ubuntu 16.04.4

**Comment by nrk** [comment]
Hi @steve75918,

`TTL` [is supported](https://github.com/predis/predis/blob/5e220a0b5787044764fc2159a767b9277a244d0f/tests/Predis/Cluster/RedisStrategyTest.php#L328) and works as expected when using redis-cluster with Predis.

See below for  the output of an interactive shell session reproducing the very same flow of commands used in you snippet:

```
>>> $client = new Predis\Client($clusternodes, ["cluster" => "redis"]);
=> Predis\Client {#2369}

>>> $client->getConnection();
=> Predis\Connection\Cluster\RedisCluster {#2356}

>>> $client->hset("key", "name1", "value1");
=> 1

>>> $client->hset("key", "name2", "value2");
=> 1

>>> $client->expire("key", 10);
=> 1

>>> sleep(5);
=> 0

>>> $client->ttl("key");
=> 5

>>> sleep(6);
=> 0

>>> $client->ttl("key");
=> -2
```
