### ISSUE TITLE
is this  support bitop function with redis-cluster

### ISSUE THREAD

**Issue by xiaobaig0407** [predis/predis#522]
when I use yii2 framework, use predis extensiton, it reports error like that.
Is it the own reason of redis-cluser  or the extension doesn't support redis-cluster bitop funciton?

Exception 'Predis\NotSupportedException' with message 'Cannot use 'BITOP' with redis-cluster.' 

in /usr/local/var/www/active-api/frontend/lib/predis/src/Connection/Cluster/RedisCluster.php:322

Stack trace:
#0 /usr/local/var/www/active-api/frontend/lib/predis/src/Connection/Cluster/RedisCluster.php(493): Predis\Connection\Cluster\RedisCluster->getConnectionByCommand(Object(Predis\Command\Redis\BITOP))
#1 /usr/local/var/www/active-api/frontend/lib/predis/src/Connection/Cluster/RedisCluster.php(536): Predis\Connection\Cluster\RedisCluster->retryCommandOnFailure(Object(Predis\Command\Redis\BITOP), 'executeCommand')
#2 /usr/local/var/www/active-api/frontend/lib/predis/src/Client.php(341): Predis\Connection\Cluster\RedisCluster->executeCommand(Object(Predis\Command\Redis\BITOP))
#3 /usr/local/var/www/active-api/frontend/lib/predis/src/Client.php(324): Predis\Client->executeCommand(Object(Predis\Command\Redis\BITOP))
#4 /usr/local/var/www/active-api/frontend/modules/activities/controllers/SignController.php(54): Predis\Client->__call('BITOP', Array)
#5 [internal function]: frontend\modules\activities\controllers\SignController->actionGetre()
#6 /usr/local/var/www/vendorlvd/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /usr/local/var/www/vendorlvd/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 /usr/local/var/www/vendorlvd/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('getre', Array)
#9 /usr/local/var/www/vendorlvd/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('activities/sign...', Array)
#10 /usr/local/var/www/vendorlvd/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /usr/local/var/www/active-api/frontend/web/index.php(30): yii\base\Application->run()
#12 {main}### ### ###

**Comment by nrk** [comment]
`BITOP` is properly implemented in Predis to support redis-cluster. The most likely issue in you case is probably that your application is passing keys to `BITOP` (destination key and source keys) that do not calculate the same hash meaning that you'd end up with a `-CROSSSLOT Keys in request don't hash to the same slot` error. See [what the official Redis documentation says](https://redis.io/topics/cluster-tutorial#migrating-to-redis-cluster) about the limitations when using multiple keys commands with redis-cluster:

> Multiple keys operations, transactions, or Lua scripts involving multiple keys are used but only with keys having the same hash tag, which means that the keys used together all have a {...} sub-string that happens to be identical. For example the following multiple keys operation is defined in the context of the same hash tag: SUNION {user:1000}.foo {user:1000}.bar.
