### ISSUE TITLE
I always have problems when use hgetall

### ISSUE THREAD

**Issue by zxzgit** [predis/predis#550]
When there is a large amount of concurrency, there is always a problem with “hgetall” 

`count(): Parameter must be an array or an object that implements Countable in /vendor/predis/predis/src/Command/HashGetAll.php at 36 line.`,
I found the "data" parameter to be an string(the content of the string is an integer) at \Predis\Command\HashGetAll::parseResponse,make this abnormal。

predis v1.1.1
Redis server v=4.0.11 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 
PHP 7.2.14 (cli)  ( NTS )
Laravel Framework Lumen (5.7.7) use Illuminate\Support\Facades\Redis 

When there is a large amount of concurrency, there is always a problem with “hgetall” 、 “hget” 、zrange. When hget is used, the data will not be found.

Also, when using lpop, you won't get the correct data, but get an integer.

This has been bothering me for a long time, sincerely hope that you will have time to reply to these questions.

**Comment by nrk** [comment]
I'm closing this due to lack of feedback, feel free to re-open it if you have more details to share and are still interested in it.
