### ISSUE TITLE
The command 'dbsize' is not allowed in replication mode

### ISSUE THREAD

**Issue by Fred07** [predis/predis#551]
when I use `dbsize` command with predis in replication mode, then I get the error below

```
Predis\NotSupportedException: The command 'DBSIZE' is not allowed in replication mode
```

but I can use this command directly in my redis

is this a library bug or it just a restriction of redis db in replicataion mode?

**Comment by nrk** [comment]
See [my comment](https://github.com/nrk/predis/issues/598#issuecomment-671876712) on #598, even if we are discussing about `INFO` in that issue the proposed solution is the same. We may discuss about changing this behaviour for future releases.

**Comment by Fred07** [comment]
Hi @nrk, thanks for your reply, and I got the solution in #598 
my current workaround for the scenario is to apply a customize `MasterSlaveReplication` and `ReplicationStrategy` which removed `dbsize` command from disallowed operators while process initiating predis client.

and it worked properly, but  i'm still looking forward to the upcoming updates for the feature about that.

glad to see this project back on track again 😀

**Comment by nrk** [comment]
> my current workaround for the scenario is to apply a customize MasterSlaveReplication and ReplicationStrategy which removed dbsize command from disallowed operators while process initiating predis client.

Yay, having the ability of customizing Predis as much as possible was after all 👍 😃

Maybe an improvement for v2.0 could be adding a set of whitelisted commands (like `INFO` or `DBSIZE`) to be executed on a master node without actually switching from the currently node the client is connected to. It would be possible to do this internally to `MasterSlaveReplication` by using `Predis\Connection\Replication\MasterSlaveReplication::getConnectionByRole()`. It's just a quick idea worth investigating, but would that work in a scenario like yours?

> glad to see this project back on track again 😀

Thank you @Fred07!

**Comment by Fred07** [comment]
> Maybe an improvement for v2.0 could be adding a set of whitelisted commands (like `INFO` or `DBSIZE`) to be executed on a master node without actually switching from the node the client is currently connected to. It would be possible to do this internally to `MasterSlaveReplication` by using `Predis\Connection\Replication\MasterSlaveReplication::getConnectionByRole()`. It's just a quick idea worth investigating, but would that work in a scenario like yours?

it sounds good to me, user only facing the predis `client` and having an option to set the whitelist, then connection strategy `MasterSlaveReplication` will handle it between master/slave, am i right for this planning behavior?

**Comment by nrk** [comment]
@Fred07 yes, generally speaking that's the idea.
