### ISSUE TITLE
Seek help !!! No sentinel server available for autodiscovery

### ISSUE THREAD

**Issue by simpson9527** [predis/predis#561]
++There are so many errors like "No sentinel server available for autodiscovery” in php logs frequently. but the sentinels and redis service are normal. at the same time, No errors or warnings in sentinel or redis log.
++our development framework is laravel
++The detail logs is:
No sentinel server available for autodiscovery. {"exception":"[object] (Predis\\ClientException(code: 0): No sentinel server available for autodiscovery. at /data/www/ic/vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php:268)

**Comment by simpson9527** [comment]
The sentinel status:
# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=sentinel-****-****,status=ok,address=****:****,slaves=1,sentinels=3
127.0.0.1:****> sentinel sentinels sentinel-****-****
1)  1) "name"
    2) "03e7cb302fff7552343fbbc9fb071f92404588a7"
    3) "ip"
    4) "****"
    5) "port"
    6) "****"
    7) "runid"
    8) "03e7cb302fff7552343fbbc9fb071f92404588a7"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "498"
   19) "last-ping-reply"
   20) "498"
   21) "down-after-milliseconds"
   22) "20000"
   23) "last-hello-message"
   24) "936"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "472"
2)  1) "name"
    2) "6f8ba8e8f5a22accf02b943b4e92e8fbd461f439"
    3) "ip"
    4) "****"
    5) "port"
    6) "****"
    7) "runid"
    8) "6f8ba8e8f5a22accf02b943b4e92e8fbd461f439"
    9) "flags"
   10) "sentinel"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "498"
   19) "last-ping-reply"
   20) "498"
   21) "down-after-milliseconds"
   22) "20000"
   23) "last-hello-message"
   24) "629"
   25) "voted-leader"
   26) "?"
   27) "voted-leader-epoch"
   28) "473"

**Comment by simpson9527** [comment]
The function "stream_socket_client" is enable in php.ini

**Comment by YuZhenXie** [comment]
I have same issue.Sometimes this error happens, sometimes not.
Environment:
PHP 7.3.7
Redis 5.0.6
Lumen 5.5.*

Any idea?

**Comment by Zaszczyk** [comment]
I also have same issue and didnt find fix or workaround.

**Comment by olavEngelsastro** [comment]
Same

**Comment by maitza** [comment]
Also have this issue, any idea?

**Comment by Gregy** [comment]
The `No sentinel server available for autodiscovery` is generic error that can hide other problems. The original exception is likely getting eaten up here: https://github.com/nrk/predis/blob/v1.1/src/Connection/Aggregate/SentinelReplication.php#L464 or here: https://github.com/nrk/predis/blob/v1.1/src/Connection/Aggregate/SentinelReplication.php#L432 Try to add debugging that prints out the $exception around those lines to get more information about the original problem. It is likely a connection issue, possibly a timeout as the default is set very low - 0.1s.
