### ISSUE TITLE
Socket read blocks PHP signals handling. Possible workaround

### ISSUE THREAD

**Issue by spajak** [predis/predis#563]
When reading from socket Predis blocks PHP's internal signal handling (SIGCHLD, SIGINT etc.). Registered handlers are not fired because reading from socket blocks completely, when `read_write_timeout` is set to `0` this means handlers are never fired. This is really a problem in my case, as I'm forking some background process to do it's work.

A possible workaround would be to read the socket in a loop with let's say 1 second timeout, instead of infinity. That will allow to process pending signals by the handlers. It could be configurable by the user with some new parameter (like `resume_read_on_timeout`).

I tried to change the code as below. It is working as expected in my environment (Debian 9, PHP 7.3):
```
// Predis\Connection\StreamConnection

public function read()
{
    $socket = $this->getResource();

    while (is_resource($socket)) {
        $chunk = fgets($socket);

        if (false === $chunk and
            isset($this->parameters->read_write_timeout) and
            $this->parameters->read_write_timeout > 0 and
            stream_get_meta_data($socket)['timed_out']
        ) {
            // The timeout is expected so re-read from the socket
            continue;
        }

        if ($chunk === false || $chunk === '') {
            $this->onConnectionError('Error while reading line from the server.');
        }

        break;
    }

    $prefix = $chunk[0];
    $payload = substr($chunk, 1, -2);

```

What do you think about such PR?

**Comment by nikeee** [comment]
I seem to have a similar issue. However, this issue was closed without any comment or resolving pr/commit. Was it resolved or do I have a different problem?

I'm creating a `pubSubLoop` and looping over the messages: `foreach ($loop as $message)`.
