### ISSUE TITLE
The Future of Predis 🚀

### ISSUE THREAD

**Issue by nrk** [predis/predis#587]
### EDIT **2020/08/21**
I think it's worth editing the original message to sum everything up for those landing here from search engines or external links: **Predis is alive again** and has a new home in the [Predis organization](https://github.com/predis/) along with a few collaborators thanks to @tillkruss who is officially a [maintainer for this project](https://github.com/predis/predis/issues/587#issuecomment-671791015). I still plan to work on Predis  when time allows 😉 Now full steam ahead! 🚀 

Below follows the original opening text of this issue.

----

I bet this won't sound surprising to many long-time users of this library at this point but the time to call for help from the community has finally come, albeit a bit late I guess. 

Just a few words on why we've reached this point. Predis has always been mostly a one-man project aside from a few good PRs and various kinds of contributions for which I'm still thankful after years. This didn't pose much issues at least until I started having less and less free time to dedicate to my opensource activity which basically amounted to zero in the last 18 months. Truth to be told part of the problem is also that I don't have the same motivation I had a few years ago to maintain such a library, but I hated to admit it. That said, if there's one thing that fueled my reluctance to call for help is that I've always been quite meticulous with my work (which doesn't mean being perfect, whatever that means) but many PRs I received in the past were admittedly sloppy, with no care for the coding style adopted by the project, glaring errors, conflicts with the overall design of the library or missing tests just to name the most striking examples of what I mean. 

So what now? Basically I'm looking for contributors that are seriously interested to help with maintaining Predis and that are willing to strive for the same meticulous approach. I don't expect people rushing here to take up on such task, the fact that Predis is a pure-PHP implementation of the Redis protocol surely attracted critics and in the meanwhile PhpRedis matured so much in terms of features and stability so there's probably less need for it, but I don't want to reach the point of having to mark this project as abandoned because I think it still has its own place in the PHP + Redis ecosystem. Obviously I'll try to help as much as possible especially when there are doubts about Predis internals and the overall design of the library, just don't take readiness for granted due to limited time.

The most urgent task is to rank open issues and fix them to push a new relase in the v1.1 branch, some open PRs address a few of these issues but they probably need some work. At first, contributors willing to help should work on their own forks to polish the code before submitting proper PRs for fixes, but if any currently open PR indeed doesn't need anything more than a merge because it passess the test suite and doesn't break anything else then let me know and I'll merge it ASAP. I may consider giving access to the main repository to contributors that earned my trust, I guess you undestand that I cannot do such a thing immediatly.

The master branch is meant to become v2.0, but since it diverged quite a lot from v1.1 most fixes cannot be easily merged. At first I intended to maintain both v1.1 and master-to-be-v2.0 but in retrospect I guess that plan actually backfired so now the plan is to just fix v1.1 for both implementation bugs and compatiblity issues with newer PHP versions, maybe a few new Redis commands, and leave it at that. On the master branch, aside from applying the same fixes, we should drop support once and for all for PEAR and older PHP versions and rework parts of code that could benefit from new features introduced in PHP 7 before implementing anything new.

I'm not sure how it will go, but let's discuss how to make it work. I'd really prefer to discuss this publicly but if you need to contact me privately then go ahead.

**Comment by rlunar** [comment]
Daniele, thank you for sharing your thoughts and be open for contributions; as I mentioned I would like to contribute to bringing back **predis** back alive, I'm a heavily Redis user and yes PhpRedis would make sense most of the time, but **predis** allows the no Extension dependency to move ahead with the code in many ways _local_, _serverless_, _containers_; hence my desire to see it moving forward.

**Comment by whiteCcinn** [comment]
Although I am not a big fan of predis, as an open source enthusiast, I do borrow the key prefix design of predis and hope that predis will become better and more modern after the reconstruction.

**Comment by renanvieira** [comment]
I don't have much of PHP expertise, so I would need some help through the code reviews for the language good practices. 

If this is not a problem, would love to help to keep Predis alive.

**Comment by srmklive** [comment]
Danielle, thank you for sharing your thoughts. I have used predis for a lot of projects and would love to be given the chance to help to keep the project alive.

**Comment by emmanix2002** [comment]
I use this library a lot and would love to help out anyway I can. ♥️

**Comment by dereuromark** [comment]
@nrk 
Spryker also uses this library right now and would be in need of it in the future.

Do you need any help here? GitHub sponsoring or in any other form?
Can we make PRs against this repo and will they still be merged?
For example, we need to test against PHP7.4+ and PHP8 compatibility (right now travis is <=7.1)

**Comment by tillkruss** [comment]
Someone needs to fork the repo and take it over. I’m sure GitHub sponsorships will follow.

**Comment by nrk** [comment]
@dereuromark actually I wouldn't be against handing the repostory altogether to a contributor acting as a maintainer provided they have a track record of quality contributions to other projects, if this would help solving the issue. The truth is I'm not able to fill such position anymore, mostly due to time but add also motivation to the mix. Don't get me wrong I'd still love to help from time to time as a contributor.

It's not really just doing the "boring" work (fixes, reviews, merges, docs), there's also a lot of stuff that needs to be done simply to get the library back on track as a project. Also, dropping PHP 5 and a few of the earliest / unsupported releases of PHP 7 would certainly benefit the design of a new and more optimized major release of Predis (I haven't investigated RESP 3.0 yet, but I guess that the library internals would need to be re-designed to support it). In the end that means there's a whole lot to do both in the short and in the log run.

It would have been be far easier if the project had a stable contributor beside me in the past so that I could let them take over the repository with "peace of mind", but that's not the case unfortunately. This is mostly the reason why I'd prefer help from users with a verifiable track record of past contributions to other projects before handing the maintainer position to anyone, after all the library is still used by many in the wild so I guess it would be bad if a new maintainer started merging bad PRs and code just for the sake of releasing stuff.

Leaving aside the few public comments posted here, after I created this issue I got only 4 private messages from people willing to help. The last one is from just a few days ago, but since I have _a bit_ of a backlog I still have to give a proper reply to the previous one I received in late May. I'd prefer to discuss with them publicly if possible, so I'll contact them in the next few days about this.

This comes at the right moment as, since yesterday, I'm finally on vacation for a couple of weeks and I won't be that busy until the end of August anyway. During the second half of August I should also be able to merge a few pending PR.

In the meanwhile I'm open to advice and suggestions on how to handle this.

**Comment by tillkruss** [comment]
@nrk: I would take it and build a little team of more contributors. 

I got plenty of open source experience and maintaining packages. Also got a paid Redis related products. Feel free to email me: https://till.im

**Comment by dereuromark** [comment]
We are happy to assist in supporting capacity.

I am sure that once the signal is sent that the project is maintained again, people will pick up and try to PR their issues again.
Right now most wouldn't as they are not sure if their work would ever find its way into the repo (being merged).
=> Looking at current PR list doesn't inspire confidence, and there is really a lot to be done to get the last years covered (Since 7.2+).

From experience, I can tell you that once confidence is regained, it will create a positive effect on the contributions, especially around the consumers of this library.

**Comment by nrk** [comment]
@tillkruss and @dereuromark first of all let me say that your offer is extremely appreciated especially because both of you are experienced developers with quite a lot of direct and indirect contributions to some great projects, I'd be reassured and thrilled to have people like you and potentially a few more contributors on board to give Predis a new chance.

I'm leaving early tomorrow for a few days up in the mountains for some treks and I'll be back on Saturday, after that we can start coordinating on the transition. Aside from fixes, one of the first things that will need to be settled is how to handle the current duality of the branches `v1.1` and `master`. Quoting what I wrote when I opened this issue:

> The master branch is meant to become v2.0, but since it diverged quite a lot from v1.1 most fixes cannot be easily merged. At first I intended to maintain both v1.1 and master-to-be-v2.0 but in retrospect I guess that plan actually backfired

In addition to that, it also made everything quite confusing in the past for those who tried to send PRs as some of them targeted `v1.1` and others targeted `master`. `v1.1` should definitely get all the fixes to glaring bugs and just a tiny bit more as it's the stable branch of the library after all, but new stuff should probably land only in `master` while it gets reworked.

> @nrk: I would take it and build a little team of more contributors.

@tillkruss that would be awesome!

> From experience, I can tell you that once confidence is regained, it will create a positive effect on the contributions, especially around the current active consumers of this library.

@dereuromark indeed everything entered a vicious cycle for a while now, I hope this will not just have a positive effects in terms of users contributing, but also on the quality of those contributions.

**Comment by tillkruss** [comment]
German takeover 🤷‍♂️

**Comment by naxvog** [comment]
Reporting for duty o7

**Comment by b1rdex** [comment]
Love to see this happening! I wrote a private message to Daniele some time ago and I'm very pleasured the question is started to solve.

**Comment by AkenRoberts** [comment]
Reading this just because I'm doing to updates on our app which uses the package. Not much to contribute other than a high five to past and future maintainers. Thank you! 🙏

**Comment by tillkruss** [comment]
We'll get Predis ready for Laravel 8 in early September 👍🏻

**Comment by AhmedRaafat14** [comment]
I would love to be one of the future maintainers as well.
I love the package and will hate to see it left like that.

Will do my best as well to open some PRs and improvements to support latest PHP or Symfony.

Will do my best :)

**Comment by tillkruss** [comment]
@AhmedRaafat14: If you want to start fixing Travis PHP 5.3 to 7.4, that would be fantastic!

**Comment by AhmedRaafat14** [comment]
Yes, would love to do that will pick that up and see where it will go with me 👌.

My comment deleted by accident 😁.

However here it's in short:
> Was saying I love the package and would like to be one of the maintainers.


Will do my best.

**Comment by nrk** [comment]
As some of you may have guessed already, I'm thrilled to announce that we officially have @tillkruss on board as the new maintainer for Predis since yesterday 🎉 This is great news as the project can finally get a new life and I'm sure it is in good hands now. At the same time, I'll try my best to stick around and contribute code or help whenever possible for me.

Don't get me wrong, that doesn't change the fact that some help would be greatly appreciated as there's actually quite a lot of stuff to be done in the long run so don't be shy and contribute if you have fixes, improvements or simply good ideas 😉

Please see #615 for a rough roadmap for the future.

Thank you @tillkruss, and everyone that offered their help.

**Comment by tillkruss** [comment]
Thanks @nrk! ❤️

Hi! I'm Till Krüss 👋🏻

I just invited a couple of people who are interested in contributing to the new [PredisHQ organization](https://github.com/predishq) and we'll migrate the repository over after we release v1.1.2 shortly, which finally comes with PHP 7.4 compatibility.

If I forgot to invite anyone interested, please let me know and I'll invite you, too.

We'll move to GitHub Sponsors for organizations. If you or your business is interested in supporting the development of this fantastic library, please click the Sponsor button above. 🙏🏻

**Comment by lonnylot** [comment]
Hi all,

I realize I'm late to the game, but I wanted to get an update on PHP version support and v2.x timeline.

I ask because Laravel 9.x is due out in ~January and it is going to be using Symfony 6.x. Symfony 6.x requires PHP >= 8.0.2.

Right now Laravel projects risk getting stuck on Laravel v8.x if they use predis. Predis may also runs the risk of being dropped as a supported Redis driver from Laravel 9.x if there is not a working version that supports PHP >= 8.0.2.

**Comment by b1rdex** [comment]
IIRC, v1 already supports php 8.

**Comment by lonnylot** [comment]
@b1rdex Oh awesome - sorry - I was going by the discussion in this issue. Thanks for the quick response!

**Comment by tillkruss** [comment]
@lonnylot We'll make sure 1.x will support PHP 8.1 as well.

**Comment by driesvints** [comment]
@tillkruss is there any news on PHP 8.1 support yet? Release date is approaching now : )

**Comment by tillkruss** [comment]
I think we fixed all issues in #712, but I'm looking into why Travis isn't running right now.

**Comment by driesvints** [comment]
Sweet. @tillkruss would be cool if we could get that tagged soon!

**Comment by visonforcoding** [comment]
heartbeat for some server with timeout config

**Comment by vini123** [comment]
虚幻之物对应着冥冥之路！：《羽》
