### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by andrew-svirin** [predis/predis#591]
I have using predis (v1.1.1) with symfony for caching purpose and have sometimes such error:

```json
{
    "class": "Symfony\\Component\\Debug\\Exception\\OutOfMemoryException",
    "message": "Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 528384 bytes)",
    "code": 0,
    "file": "..../vendor/predis/predis/src/Connection/StreamConnection.php:391"
}
```

Reffering on this row: https://github.com/nrk/predis/blob/v1.1.1/src/Connection/StreamConnection.php#L391

Do i need to suspect predis? or is it some server error?

**Comment by Uranbold** [comment]
How did you resolve it?

**Comment by andrew-svirin** [comment]
We had some php memory_limit occasion.  So check if you have 256MB of memory delegated.

**Comment by nrk** [comment]
Hi @andrew-svirin, it's pretty much impossible to answer your question without any kind of tracing or knowing what your application actually does under the hood when this happens.

Obviously if you try sending an humongous payload to Redis or keep large response payloads (especially _multibulk_ ones) in memory or build huge pipelines up without gradually flushing them to the server then I guess it wouldn't be surprising to hit `memory_limit` depending on your environment configuration and the actual complexity of the whole application.

There's no PHP native output buffering mechanism involved in Predis by the way, but right now the actual wire protocol for the request is indeed wholly serialized to a string buffer before writing it to the network, this could probably be improved in future releases but it's not in our priorities I'd say.

**Comment by alagiyanirav** [comment]
I have set memory_limit = -1 but still facing the same issue. 
What is the possible solution to this issue?
I really appreciate any help on this issue.

**Comment by 80boys** [comment]
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /Users/wheng/phpDevelopment/UtalkLearn/vendor/predis/predis/src/Connection/AbstractConnection.php on line 144
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /Users/wheng/phpDevelopment/UtalkLearn/vendor/workerman/workerman/src/Worker.php on line 2323

me too

**Comment by ro0NL** [comment]
pretty sure we have memory issues due to predis as well

**Comment by ro0NL** [comment]
im gonna test native php ext-redis to compare

**Comment by ro0NL** [comment]
>  it's pretty much impossible to answer your question without any kind of tracing or knowing what your application actually does under the hood when this happens

nobody does, we want to know if predis has a memory leak
