### ISSUE TITLE
Replication mode: NotSupportedException case dependent

### ISSUE THREAD

**Issue by DemigodCode** [predis/predis#598]
I don't really know what's the right behaviour here. 
I'm running Master/Slave-Replication and the NotSupportedException is thrown if I run the info command.
If I do some write requests, all is fine running the info command. But if I didn't write anything before running info() the NotSupportedException is thrown.

What's the right behaviour?
Are all disallowed commands disallowed everytime or do we have to switch to master when running those commands? AFAIK phpredis isn't doing anything like that and just uses the master.

There are other questions like https://github.com/nrk/predis/issues/551 and https://github.com/nrk/predis/issues/596

IMO, those commands can be safely send to the master.

But no answer. Is anyone maintaining this project?

**Comment by nrk** [comment]
Hi @DemigodCode,

Yes `INFO` is currently disallowed by choiche even if it's not like it wouldn't work per se. The rationale behind the decision to not allow it to be used directly in a replication scenario is that:

1. `INFO` would hit a random slave node, which wouldn't make much sense to me.

2. Having it redirected to the master node would involve a permanent switch for the rest of subsequent commands in the script (that is, unless you force the client to go back to using slave with [`$client->getConnection()->switchToSlave()`](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Aggregate/SentinelReplication.php#L598-L605));

That said, you can indeed explicitly direct any command to a specific node (e.g. the master one or even a specific named slave in case of replication) by using something along these lines:

```php
$masterNode = $client->getClientFor("master");
$masterNode->info();
```

The benefit of this approach is that the main client isn't forced to switch from the current slave and you are also able to explicitly tell from which node you actually want to get the `INFO` payload from (or even query all of the nodes). This will work for any command by the way, except a Redis node may return a `-ERR` reply when the command is indeed not allowed when using redis-sentinel.

Does it make sense now with this explanation?

> But no answer. Is anyone maintaining this project?

We have Predis back on track, finally 😉

**Comment by acelaya** [comment]
I don't want to revive an old issue, but I'm trying to do what's described here, but for predis 2.

According to the [changelog](https://github.com/predis/predis/blob/main/CHANGELOG.md#v200-2022-06-08), `getClientFor` has been replaced by `getClientBy`, however this one expects more arguments, and it actually fails if the first one is "master".

What would be the right way to run a command against the master instance on a replication connection using predis 2?

**Comment by acelaya** [comment]
Ok, my mistake, I was actually doing it wrong 😅 

`$predis->getClientBy('role', 'master')` Does the same on predis 2.
