### ISSUE TITLE
Unable to catch exceptions

### ISSUE THREAD

**Issue by Alexia** [predis/predis#61]
Version 0.7.1 and 0.7.2-dev.  It is impossible to catch Predis\Network\ConnectionException exceptions.  I have tried multiple ways I can think of to fix this, but so far are unable to.

``` php
        include_once('Predis/Autoloader.php');
        Predis\Autoloader::register();
        try {
            $this->redis = new Predis\Client($this->config['redis_servers'], array('prefix' => $this->config['db']['sql_database'].':', 'throw_errors' => false));
        } catch (Predis\Network\ConnectionException $e) {
            var_dump($e);
        }
```

**Comment by gagarine** [comment]
I agree this should be documented...

**Comment by MaxymVlasov** [comment]
For version 1.1
```php
$client = new Predis\Client();

try {
    $client->connect();
}
catch (Predis\Connection\ConnectionException $exception) {
    // do stuff to handle the fact that you weren't able to connect to the server
    // here I'm using exit() just as a quick example...
    exit("whoops, couldn't connect to the remote redis instance!");
}

$client->info();
```

**Comment by xZero707** [comment]
Calling 
> Predis\Client::connect()
 explicitly didn't worked for me. 
Predis\Connection\ConnectionException is still "escaping".

**Comment by cendekia** [comment]
> Calling Predis\Client::connect() explicitly didn't worked for me. Predis\Connection\ConnectionException is still "escaping".

same here, is there any solution?

**Comment by alefalves** [comment]
> > Calling Predis\Client::connect() explicitly didn't worked for me. Predis\Connection\ConnectionException is still "escaping".
> 
> same here, is there any solution?

@cendekia you can just do something like that:

```
try {
      self::$Connect = new Predis\Client(self::getConfig()); 
       self::$Connect->connect();
       if (!self::$Connect) {
            throw new Predis\Connection\ConnectionException('Redis doesn`t connect')
        }
} catch (Predis\Connection\ConnectionException $e) {
       Request::redirect('error/503');
       die;
}
```
I've not implemented any logging service yet, but you can get the error data in the variable $e
