### ISSUE TITLE
Roadmap to v2.0

### ISSUE THREAD

**Issue by tillkruss** [predis/predis#615]
Some thoughts on the future roadmap.

## v1.1

- Bug fixes only
- Maintain support for PHP 5.6 - 7.4 and Redis 3-5

_PHP 7.2 is EOL will get security patches only until 30 Nov 2020._

## v2.0

- Drop HHVM & PEAR
- Support PHP 7.2 - 8.0
- Merge new features and new Redis commands
- Support for Redis 3-6?
- API documentation?
- Move to GH Actions?

**Comment by tillkruss** [comment]
Ping @AhmedRaafat14 @b1rdex @dereuromark @emmanix2002 @srmklive @rlunar.

**Comment by b1rdex** [comment]
V1 branch should get full php < 8 support. May be php 8 too if that doesn't require too much changes. We use predis with php 7.4 in production with no bugs found.

**Comment by tillkruss** [comment]
@b1rdex That depends on PHPUnit. If we can find a version that supports 5.3 - 7.4, sure. If not we might need to branch off v1.2 that supports 5.6 - 7.4, but drops anything older.

**Comment by b1rdex** [comment]
It’s possible to patch phpunit using composer patches to get even phpunit 4.8 to work with php 8. Example: https://github.com/yiisoft/yii/pull/4306

Отправлено с iPhone

**Comment by tillkruss** [comment]
@b1rdex Neat, can you open a PR test v1.1 with 7.3 and 7.4?

**Comment by emmanix2002** [comment]
What do you need yes to do @tillkruss ?

**Comment by AhmedRaafat14** [comment]
Cool!
I completely agree with @b1rdex `v1.1` should get the full support for `PHP < 8`, and the same for `v2.0`.

As @tillkruss suggested we can call it `v1.2`.

We use Predis with PHP 7.2 & Symfony 4.4 in production with no bugs so far.

So it should be easy & neat.

**Comment by nrk** [comment]
I'd also drop PEAR support, at least from v2.0 and going forward.

Honestly it's always been a nightmare to have it build packages of Predis on each release as I had various problems in the past with getting the build environment running properly from time to time (the actual build process also requires [some hackish stuff](https://github.com/nrk/predis/blob/dbfc1a74ba524636af2e3ef2c6d330d39098345f/bin/create-pear)). Furthermore I guess PEAR is a dead man walking anyway.

I'll try to get it work for the next patch release at least.

**Comment by dereuromark** [comment]
Also v2 should be PHP7.2+ then (no need or usefulness in anything below), especially with PHP8+ compatibility in planning as well.

**Comment by nrk** [comment]
> Also v2 should be PHP7.2+ then (no need or usefulness in anything below), especially with PHP8+ compatibility in planning as well.

PHP 7.1 and 7.2 added quite a lot of interesting features that could be useful in to improve the codebase while PHP 7.3 didn't add much to the table in this respect so having PHP 7.2 as the minimum required PHP version for v2.0, even if it will soon reach EOL, would make sense to me.

**Comment by srmklive** [comment]
I would also suggest that we drop support for hhvm for v1.1 and have it support php > 5.6 & <8.

**Comment by dereuromark** [comment]
Agreed. Most frameworks/libraries also dropped HHVM quite some time ago. There is no point in trying to artificially force this support any longer.

**Comment by dereuromark** [comment]
if v1.1 can be 7.4 inclusive, that would be nicer for people to upgrade to 2.0 then (as many systems can then use latest v1.1 and switch more gracefully to v2).
There arent that many PHP73/PHP74 topics here that would be a problem here tbh.

**Comment by nrk** [comment]
> I would also suggest that we drop support for hhvm for v1.1 and have it support php > 5.6 & <8.

@srmklive hmmm honestly I'd be wary of restricting the minimum required PHP version or runtime on a patch release in the `v1.1` branch, but we could indeed do that for `v1.2` if we end up deciding to have an intermediate branch before going full steam ahead with the `master` branch which should be the future `v2.0`.

> if v1.1 can be PHP 7.4 inclusive, that would be nicer for people to upgrade to v2 then (as many systems can then use latest v1.1 and switch more gracefully to v2).

@dereuromark I'm still having a look at pending stuff but if the only real blocking issue in order to have `v1.1` targeting PHP 7.4 is just related to phpunit then I guess @b1rdex's [tip](https://github.com/nrk/predis/issues/615#issuecomment-671675444) would be indeed worth a try, it'd be a shame if we ended by being limited just by phpunit after all.

**Comment by dereuromark** [comment]
True, I didnt mean patch, but minor release (so any 1.2 etc would be fine) of course.

**Comment by AhmedRaafat14** [comment]
I would say that we go with minor release `v1.2` (small bug fixes, small code improvements if possible, compatible with `PHP <= 7.2`...etc), then we target most of the new things like PHP compatibility `7.2 > PHP < 8.0`, introduce new profiles & commands..etc to `v2.0`.

We use this minor release `v1.2` as an announcement that the package is back into action 😉 and everyone else watches out 😁.

Just an idea, if this doesn't make sense so we just target everything new to `v2.0`!

**Comment by dereuromark** [comment]
1.2 should still be 7.4 incl as mentioned before if there is compelling reason against it (which there shouldn't be).
See also travis matrix of PR that is not yet merged. It will be easy to get this done.

**Comment by AhmedRaafat14** [comment]
@dereuromark yes, just saw the PR and it should be easy as also mentioned above people already running the package on PHP 7.4 with no bugs.

Agree & updated my comment :).

**Comment by tillkruss** [comment]
Like @nrk mentioned, any breaking changes will go into v2.0 to stick with SemVer, so people are confident nothing breaks during updates.

We can go as low as 7.0 or 7.2 for the v2.0 branch, if that increases backwards compatibility.

See #616 for PHP 7.4 support on v1.1.

**Comment by tillkruss** [comment]
I just claimed `predishq` (PredisHQ) as an GitHub organization. Any objections?

**Comment by emmanix2002** [comment]
> I just claimed `predishq` (PredisHQ) as an GitHub organization. Any objections?

None! Good job!

**Comment by tillkruss** [comment]
I've invited you guys to `predishq`, did I forget anyone?

I was thinking of pushing v1.1.2 shortly and moving the repo afterwards.

**Comment by tillkruss** [comment]
I've created a project to manage the v2.0 release: https://github.com/nrk/predis/projects/1
