### ISSUE TITLE
Drop HHVM support

### ISSUE THREAD

**Issue by tillkruss** [predis/predis#618]
Like most PHP packages, let's drop HHVM support in v2.0. v1.1 will continue to support it, but will only receive bug fixes.

**Comment by srmklive** [comment]
I think its already removed as per this commit for v1.1: cf15dd9857649ca65976ceebb360fe105328cbd6

**Comment by tillkruss** [comment]
Yeah, this is mostly to remove leftovers.

**Comment by nrk** [comment]
Fixed in #654.
