### ISSUE TITLE
Support PHP 8, drop PHP 5 & 7.0 - 7.1

### ISSUE THREAD

**Issue by tillkruss** [predis/predis#620]
As discussed in #615. Related #616.

**Comment by dereuromark** [comment]
This seems to be already done in https://github.com/nrk/predis/blob/main/.travis.yml (main)
and can be closed then.

**Comment by tillkruss** [comment]
@dereuromark: I'll keep this open until the tests pass again.

Are you up for fixing the test failures on `main` that came with the PHPUnit upgrade from 4 to 8?

**Comment by AhmedRaafat14** [comment]
> @dereuromark: I'll keep this open until the tests pass again.
> 
> Are you up for fixing the test failures on `main` that came with the PHPUnit upgrade from 4 to 8?


I can help with this if needed as well :).

**Comment by dereuromark** [comment]
I didnt see the test fails
@AhmedRaafat14 much appreciated.

**Comment by tillkruss** [comment]
@AhmedRaafat14: Go for it 👍🏻

**Comment by tillkruss** [comment]
@emmanix2002 @AhmedRaafat14 You can split it up, too, so we have many small PRs and not one massive one 🙂

There seem to be quite a few sectors:

- Depreciation notices
- Redis 6 changes
- Broken mocks

**Comment by AhmedRaafat14** [comment]
I was just thinking about the same thing.

@emmanix2002 you can tell what you already started fixing and I can take another point, what do you think :)!

Otherwise, I will just start looking into the docs 😉

**Comment by emmanix2002** [comment]
@AhmedRaafat14 fixed issues for some of the files inside of `tests/PHPUnit` for now, specifically:

- `tests/PHPUnit/ArrayHasSameValuesConstraint`
- `tests/PHPUnit/PredisTestCase`
- `tests/PHPUnit/RedisCommandConstraint`

Currently on:

- `tests/PRedis/ClientExceptionTest`

There are quite a number of issues but the ones in the `PHPUnit` directory are the lowest hanging fruits

**Comment by emmanix2002** [comment]
@AhmedRaafat14 quick question, I don't know if we want to set `namespace` declarations inside the test files. IMO, we should only use namespace declarations for the actual source file.

I ask because the files inside `tests/Predis` have namespace declarations on them.

What do you think?

**Comment by AhmedRaafat14** [comment]
> I ask because the files inside `tests/Predis` have namespace declarations on them.


If am doing that I will use `namesspaces` for sure I love having everything inside a specified namespace and not just laying around (I think laravel doesn't have namespace for tests not sure about that but remember something like that!) but tobh it confuses me sometimes 😂.

So I would suggest yes please use `namespaces`.

**Comment by emmanix2002** [comment]
@AhmedRaafat14 😂 Cool, we'll maintain the namespaces.

**Comment by tillkruss** [comment]
We just dropped Travis for 2.0 and added GitHub actions 👍🏻

**Comment by nrk** [comment]
I guess this can be closed now?

We've done everything described here: `v1.1` targets PHP 5.3 ~ 8.0 and `main` targets PHP 7.2 ~ 8.0, test suites for these branches were fixed accordingly and they are green for both.
