### ISSUE TITLE
Move to GH actions

### ISSUE THREAD

**Issue by tillkruss** [predis/predis#621]
Do we want to move to GitHub actions for the v2.0 branch? It would make it easy to test various Redis and PHP versions in a matrix.

**Comment by nrk** [comment]
I can't really comment on GitHub actions because I've never used them. Any benefit from using them?

**Comment by tillkruss** [comment]
I was thinking to test Redis 3.x with all supported PHP versions, then Redis 4.x and so on... at least that's what I've been doing with [objectcache.pro](https://objectcache.pro)

**Comment by AhmedRaafat14** [comment]
I like this and I think the best benefit point we will get is having everything in one place which is GitHub.

**Comment by nrk** [comment]
> I was thinking to test Redis 3.x with all supported PHP versions, then Redis 4.x and so on... at least that's what I've been doing with objectcache.pro

Sounds cool!

**Comment by tillkruss** [comment]
@predishq/team: Anybody up for setting this up?

**Comment by mfn** [comment]
> predishq/team

![image](https://user-images.githubusercontent.com/87493/90063133-31402700-dce9-11ea-9d50-8e730f67bc5a.png)

Is it necessary to have this private? 🤔

**Comment by tillkruss** [comment]
@mfn: It's a public team: https://github.com/orgs/predishq/teams

**Comment by srmklive** [comment]
@tillkruss let me look into this.

**Comment by srmklive** [comment]
Just to confirm, *main* branch is where changes would be merged?

**Comment by tillkruss** [comment]
Yeah, main is the new master since BLM 👍🏻

**Comment by mfn** [comment]
> It's a public team

I stand correct, thank you! Just though the direct link could/should work.

Good day to make a fool of myself, apologies 🤷‍♀️

**Comment by mfn** [comment]
Wait, no, actually not. I can't see anything there:
![image](https://user-images.githubusercontent.com/87493/90102098-2f558280-dd40-11ea-95c8-52e89f2546c7.png)


Ok, not a big deal anyway, just wanted to point it out => I'll see myself out 😏

**Comment by tillkruss** [comment]
Solved in #634 and d4a170d.
