### ISSUE TITLE
Moved GitHub organizations

### ISSUE THREAD

**Issue by tillkruss** [predis/predis#635]
We just moved GitHub organization again to `predis`. The previous owner let it go.

- [x] Update all references
- [x] Make sure Travis works
- [x] Make sure Packagist webhook works

**Comment by tillkruss** [comment]
JFYI: @predis/team

**Comment by nrk** [comment]
> We just moved GitHub organization again to predis. The previous owner let it go.

Awesome! 🎉
I guess we should also thank the previous owner, whoever it was 😉

**Comment by tillkruss** [comment]
@nrk: The GitHub support did not tell me 😐

**Comment by tillkruss** [comment]
Packagist works.
