### ISSUE TITLE
1.1.2 lost composer v2 support

### ISSUE THREAD

**Issue by dereuromark** [predis/predis#642]
We are already using composer v2 in experimental state
But now, it seems 1.1.2 patch made composer v2 not usable again

Can we please revert this?

https://github.com/predis/predis/blob/v1.1/composer.json#L35
Why was this tool added? This seems to cause the blocking.
If we removed that in some way, composer v2 would work again

**Comment by dereuromark** [comment]
I see it was already being moved to require-dev https://github.com/predis/predis/commit/6dd55d7f9661b135964d6df49e1a126d7d1351aa#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
So if this was to be released as patch it would directly fix the issue.

**Comment by tillkruss** [comment]
@dereuromark: Does installing `v1.1.x-dev` work fine with Composer 2?

**Comment by tillkruss** [comment]
Related #632.

**Comment by tillkruss** [comment]
Related https://github.com/cweagans/composer-patches/pull/321

**Comment by dereuromark** [comment]
Still:
If you release now as I recommended, then the problem would already go away now as that dependency should never have been a require one to begin with.

**Comment by nrk** [comment]
By the way, I see a bunch of patch files commited in `v1.1` (namely `tests/phpunit_mock_objects.patch`, `tests/phpunit_php7.patch ` and `tests/phpunit_php8.patch `). Shouldn't they be added to `.gitignore` and removed from the repository?

**Comment by tillkruss** [comment]
If the patches aren't included, the dev install fails. Since we don't include the tests folder, it might make sense to move the patches into a separate folder. 

That's one of the reasons why I didn't want to keep patching PHPUnit in 2.x 👍🏻

**Comment by nrk** [comment]
> If the patches aren't included, the dev install fails. Since we don't include the tests folder, it might make sense to move the patches into a separate folder.

Alright I see, I was just asking because I still haven't had a look at what this thing does under the hood 😃

> That's one of the reasons why I didn't want to keep patching PHPUnit in 2.x 👍🏻

Indeed. In v1.1 we are just stuck with ancient stuff, but v2.0 is a whole different matter  🚀

**Comment by tillkruss** [comment]
Pushed v1.1.3 live.
