### ISSUE TITLE
set command how to write ex,nx simultaneously 

### ISSUE THREAD

**Issue by hlbbt** [predis/predis#647]
I want to write `$redis->set('tab', 1, ['nx', 'ex' => 60])` such commands, but it doesn't seem to be;
I want to learn how to write such commands

**Comment by nrk** [comment]
Hi @hlbbt,

Predis for `SET` does not yet support passing modifiers as an array in the last argument of the method, but as usual nothing stops you from using the same signature [described on the Redis docs for this command](https://redis.io/commands/set) so `$redis->set('tab', 1, 'ex', '60', 'nx')`.

**Comment by hlbbt** [comment]
> Hi @hlbbt,
> 
> Predis for `SET` does not yet support passing modifiers as an array in the last argument of the method, but as usual nothing stops you from using the same signature [described on the Redis docs for this command](https://redis.io/commands/set) so `$redis->set('tab', 1, 'ex', '60', 'nx')`.

Hello, it's the right way to use it, I tried all sorts of ways, 
eg: `$redis->set('tab', 1, 'ex|nx', 60)`,   `$redis->set('tab', 1, 'ex nx', 60)`,   $redis->set('tab', 1, 'nx', 60)`,  $redis->set('tab', 1, 'nx', 60, 'ex')`,

Then it seems to ignore the way you say 
Thanks very much.
