### ISSUE TITLE
Missing command LPOS

### ISSUE THREAD

**Issue by sgc-fireball** [predis/predis#652]
https://redis.io/commands/lpos

```
<?php

namespace Predis\Command;

class ListPosition extends Command
{
    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return 'LPOS';
    }
}
```

**Comment by nrk** [comment]
Hi @sgc-fireball, actually it's not just `LPOS` as we are missing all of the commands added in Redis 4, 5 and 6. Adding support for a missing command in a proper way [is not as immediate as it might seem](https://github.com/predis/predis/pull/593#issuecomment-671855512) so it could still take a bit longer to get Predis on par again with Redis, but in the meanwhile nothing stops you from using [`Predis\Client::executeRaw()`](https://github.com/predis/predis/blob/v1.1.3/examples/executing_redis_commands.php#L43-L49).
