### ISSUE TITLE
Predis v1.1.5 with Redis Sentinels - No sentinel server available for autodiscovery.

### ISSUE THREAD

**Issue by booooza** [predis/predis#658]
**Describe the bug**
After updating to Predis v1.1.5 we were unable to connect to Redis Sentinels (v3.2.3)

**To Reproduce**
```
$sentinels = [
    'tcp://host0:port',
    'tcp://host1:port',
    'tcp://host2:port',
];
$options = [
    'replication' => 'sentinel',
    'service' => 'myservice',
    'parameters' => [
        'password' => 'password',
        'database' => 0,
    ],
];

$client = new Predis\Client($sentinels, $options);
$client->set('foo', 'bar');
$value = $client->get('foo');
```

Gives us `No sentinel server available for autodiscovery.` After reverting to Predis v1.1.4 everything is working again.
Using `tcp://host0:port?password=secret` without using the password in global parameters client option does not work on our Redis server: `Predis\Connection\ConnectionException: `AUTH` failed: ERR unknown command 'AUTH'`.

**Versions:**
 - Predis: 1.1.5
 - PHP 7.2.32
 - Redis Server 3.2.3

**Comment by nrk** [comment]
@booooza hmmm sounds strange, I tested it (I mean aside from just running the test suite) before shipping the release. 

How are your sentinels and actual redis nodes configured? I mean are they both protected by a password and, if so, do they share the same password? Or is your password just for Redis nodes and sentinels are unprotected

Before 1.1.5 as far as I know there was no way to configure Predis to send a password to sentinels so they should be unprotected by `requirepass` in your `sentinel.conf`. With 1.1.5 you must put the password for sentinels in the connection parameters for each sentinel **and** keep the global password parameter for Redis nodes in the global connection parameters (`parameters` passed in client options).

**Comment by nrk** [comment]
By the way would it be possible for you to post here the stack trace of the `Predis\Connection\ConnectionException` exception being thrown with the message `AUTH failed: ERR unknown command 'AUTH'`?

**Comment by booooza** [comment]
@nrk we're using a redis enterprise cloud service so I don't have the exact configuration details. But as per you question I assume the latter is true (password just for Redis nodes and sentinels are unprotected) as I only get a single password.

```
nc -v master 1234 <- (this is an administrative address which always points to the currently elected master)
Connection to master 1234 port [tcp/*] succeeded!
PING
-NOAUTH Authentication required.

nc -v sentinel-0 5678
Connection to sentinel 5678 port [tcp/*] succeeded!
PING
+PONG
```

The stack trace of the `Predis\Connection\ConnectionException` is the following (I've replaced host and ports):

```
Predis\Connection\ConnectionException: `AUTH` failed: ERR unknown command 'AUTH' [tcp://sentinel-0:5678] in /predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /predis/predis/src/Connection/StreamConnection.php(263): Predis\Connection\AbstractConnection->onConnectionError('`AUTH` failed: ...', 0)
#1 /predis/predis/src/Connection/AbstractConnection.php(180): Predis\Connection\StreamConnection->connect()
#2 /predis/predis/src/Connection/StreamConnection.php(288): Predis\Connection\AbstractConnection->getResource()
#3 /predis/predis/src/Connection/StreamConnection.php(394): Predis\Connection\StreamConnection->write('*3\r\n$8\r\nSENTINE...')
#4 /predis/predis/src/Connection/AbstractConnection.php(110): Predis\Connection\StreamConnection->writeRequest(Object(Predis\Command\RawCommand))
#5 /predis/predis/src/Connection/Aggregate/SentinelReplication.php(349): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\RawCommand))
#6 /predis/predis/src/Connection/Aggregate/SentinelReplication.php(429): Predis\Connection\Aggregate\SentinelReplication->querySentinelForMaster(Object(Predis\Connection\StreamConnection), 'sentinel...')
#7 /predis/predis/src/Connection/Aggregate/SentinelReplication.php(501): Predis\Connection\Aggregate\SentinelReplication->getMaster()
#8 /predis/predis/src/Connection/Aggregate/SentinelReplication.php(541): Predis\Connection\Aggregate\SentinelReplication->getConnectionInternal(Object(Predis\Command\StringSet))
#9 /predis/predis/src/Connection/Aggregate/SentinelReplication.php(663): Predis\Connection\Aggregate\SentinelReplication->getConnection(Object(Predis\Command\StringSet))
#10 /predis/predis/src/Connection/Aggregate/SentinelReplication.php(703): Predis\Connection\Aggregate\SentinelReplication->retryCommandOnFailure(Object(Predis\Command\StringSet), 'executeCommand')
#11 /predis/predis/src/Client.php(331): Predis\Connection\Aggregate\SentinelReplication->executeCommand(Object(Predis\Command\StringSet))
#12 /predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\StringSet))
#13 /test.php(19): Predis\Client->__call('set', Array)
#14 {main}Predis\Connection\ConnectionException: `AUTH` failed: ERR unknown command 'AUTH' [tcp://sentinel-1:5678] in /predis/predis/src/Connection/AbstractConnection.php:155
```

**Comment by nrk** [comment]
Thanks for the additional details, will try reproducing the issue in the afternoon. Thank you!

**Comment by nrk** [comment]
There was indeed a bug, the `password` parameter from global parameters in client options was still being passed to sentinels when sentinels had no password set. Reverted the change and released v1.1.6 for now, will investigate for a proper fix.

Thank you again for reporting and sorry for the trouble!

**Comment by abmmhasan** [comment]
Seems like the issue is back with 2.0!!!!

**Comment by dunghv** [comment]
I have the same issues with version 2.0

**Comment by wuyuhang18325533531** [comment]
common issue with version 2.0,

It's a pity to use tls to connect to the sentinel, but unfortunately, it keeps reporting an error

```js
$sentinels = [
    [
        'scheme' => 'tls', 
        'ssl' => ['verify_peer' => false],
        'host' => "XXXXXXXX",
        'port' => 26379,
    ],
    // 'tcp://com-redis-redis-ha.com-redis.svc.cluster.local:26379',
];
$options = [
    'sentinel_timeout' => 5.0,
    'update_sentinels' => true,
    'replication' => 'sentinel',
    'service'     => 'mymaster',
    'parameters'  => ['database' => 2, 'password' => 'XXXX'],
];

print_r($sentinels);
print_r($options);
$redis = new \Predis\Client($sentinels, $options);
```
