### ISSUE TITLE
Error while reading line from the server on long running cli script

### ISSUE THREAD

**Issue by jupitern** [predis/predis#661]
**Describe the bug**
Hi. I have a long running script in cli mode and I need a persistent connection to redis. I am connecting with the code bellow but from time to time (a few minutes interval) I get the error:
Error while reading line from the server. [tls://...] 

**Versions (please complete the following information):**
 - Predis: 1.1.6
 - PHP 7.4
 - Redis Server 5.0.9
 - OS Debian 10

**Code sample**
````
$redis = new Client([
                'scheme'     => $redisConfig['scheme'],
                'host'       => $redisConfig['host'],
                'port'       => $redisConfig['port'],
                'database'   => $redisConfig['database'],
                'password'   => $redisConfig['password'],
                'ssl'        => $redisConfig['ssl'],
                'persistent' => true
            ], [
                'connections' => [
                    'tcp'  => 'Predis\Connection\PhpiredisStreamConnection',
                    'unix' => 'Predis\Connection\PhpiredisSocketConnection',
                ],
        );

**Comment by nrk** [comment]
@jupitern `persistent` is completely useless for long-running scripts, please read about what persistent connection resources are and their common use cases on [the PHP documentation](https://www.php.net/manual/en/features.persistent-connections.php)). What you need to do in your case is disabling the timeout on the underlying socket/stream resource, you can achieve that setting `read_write_timeout` to `0`. This will always leave the connection to Redis open even when there's no traffic between the client and the server, unless there's an actual connection error.

**Comment by jupitern** [comment]
Hi @nrk .
Thanks for your answer. Is it possible to leave the connection open indefinitely using tcp connection?
At this point I am capturing the Predis\Connection\ConnectionException and reconnecting.

**Comment by nrk** [comment]
> Thanks for your answer. Is it possible to leave the connection open indefinitely using tcp connection?

_Indefinitely_ does not exist, connections can and do break. Aside from disabling the timeout on the socket you cannot do anything about that, so you just have to deal with it by reconnecting when the connection is closed (accidentaly due to an error of forcibly by the remote host). If you need a slightly more complex logic to handle reconnections, you can wrap or subclass the client and roll your own reconnection strategy.

**Comment by jupitern** [comment]
already done that. thanks!
