### ISSUE TITLE
Frequent errors sayings "Error while reading line from the server."

### ISSUE THREAD

**Issue by tanqinwang** [predis/predis#667]
When migrate php from 5.6.40 to 7.4.7, php-fpm got connect lost frequently, especially in use pipeline command.
But with php 5.6.40, this happen less.

**Versions:**
 - Predis: 1.1.3
 - PHP 7.4.7
 - Redis Server 2.8.24
 - Ubuntu 18.04

**Predis settings**
timeout: 0.5
read_write_timeout: 1
persistent: true

redis use Amazon ElastiCache standalone mode

**Comment by StagasaurusRex** [comment]
@tanqinwang Were you able to solve this? I'm experiencing something similar

**Comment by tanqinwang** [comment]
updated the redis to 6.x version
