### ISSUE TITLE
Failed to apply the patch. Halting execution!

### ISSUE THREAD

**Issue by 4n70w4** [predis/predis#671]
**Describe the bug**

**To Reproduce**
1. Run command `composer install`
2. See error

```
Writing lock file
Generating optimized autoload files
Processing patches configuration
  - Applying patches for phpunit/phpunit (2)
    ~ predis/predis: ./tests/phpunit_php7.patch [NEW]
      Fix PHP 7 compatibility
      Failed to apply the patch. Halting execution!
      Probable causes for the failure:

      > PATCH
        @ b/src/Util/Getopt.php
        ! Hunk #1 FAILED at 35.

      (For full, unfiltered details please use: composer patch:apply -vvv)
```

**Expected behavior**

No error.

**Versions (please complete the following information):**
 - Predis: 1.1.6
 - PHP: 7.4.7

**Comment by 4n70w4** [comment]
The same error after `rm -rf vendor/` and `composer install`

**Comment by 4n70w4** [comment]
This problem appeared in version 1.1.2. No problem with `predis/predis:1.1.1`.

**Comment by nrk** [comment]
I guess this is related to #660.

**Comment by nrk** [comment]
I'm closing this issue just to concentrate focus the discussion on one thread.
@4n70w4 feel free to chime in on #660 if you have ideas, thanks!.
