### ISSUE TITLE
Release v1.1.7

### ISSUE THREAD

**Issue by claudiu-cristea** [predis/predis#672]
**Is your feature request related to a problem? Please describe.**

We're on the latest `v1.1.6` and, in order to avoid the patching, which is erroneous because `./test` is not included in the stable package, we have to do this:
```json
        "patches-ignore": {
            "predis/predis": {
                "phpunit/phpunit-mock-objects": {
                    "Fix PHP 7 and 8 compatibility": "./tests/phpunit_mock_objects.patch"
                },
                "phpunit/phpunit": {
                    "Fix PHP 7 compatibility": "./tests/phpunit_php7.patch",
                    "Fix PHP 8 compatibility": "./tests/phpunit_php8.patch"
                }
            }
        }
```

But the `main` branch always has the fix.

**Describe the solution you'd like**

Release `Release v1.1.7`.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by nrk** [comment]
@claudiu-cristea thanks but we already know that this should be fixed, see (and maybe join?) the ongoing discussion on #660 on this matter. By the way it's not that `main` has a fix, it's simply that `main` does not support older PHP releases like we do for `v1.1` so with the code in `main` there's no need to patch PHPUnit to have tests running starting from PHP 5.4 up to PHP 8.0.
