### ISSUE TITLE
I am getting this error can anyone help?

### ISSUE THREAD

**Issue by Mohit8982** [predis/predis#675]
Parse error: syntax error, unexpected '?' in C:\wamp64\www\php_redis\redis-session-php\modules\predis\src\Command\RedisFactory.php on line 42

**Comment by ivanpepelko** [comment]
Are you using php version ^7.2?

**Comment by jimbonator** [comment]
I assume you're using a recent version of Predis?  That [code](https://github.com/predis/predis/blob/338ba6d73d1293259953793a2c2b41e509b964c1/src/Command/RedisFactory.php#L42) in `master` is:
```
    public function getCommandClass(string $commandID): ?string
```
[Nullable return types](https://wiki.php.net/rfc/nullable_types) (the `?string`) were added in [PHP 7.1](https://prototype.php.net/versions/7.1/).  Which version of PHP are you using?

**Comment by tillkruss** [comment]
@Mohit8982: if you're on an older PHP version, use the `v1.1 branch`.
