### ISSUE TITLE
Cannot set timeout for redis connection using sentinel

### ISSUE THREAD

**Issue by bernardwiesner** [predis/predis#677]
**Describe the bug**
When using sentinel configuration there is no way to specify the timeout for the communication between sentinel (predis) and redis. The only timeout that can be set is the timeout between the client and sentinel.

Always the default timeout of 5 seconds is used if the redis hosts are unreachable by sentinel, and sentinel will attempt 20 times to connect, every times waiting up to 5 seconds. 

This is an issue because this can mean that your app could be hanging for 20 * 5 = 100 seconds, before sentinel throws an exception and exits. 

If possible would be good to pass some additional parameter such as `redis_timeout` to specify the timeout for communication between sentinel and redis.

Its also not possible to set `read_write_timeout` option.

**Comment by tarjei** [comment]
I got a similar bug where I cannot tell sentinel that it must use tls for the connections to the redis hosts.
