### ISSUE TITLE
ERROR: Command 'OFFSETGET' is not a registered Redis command

### ISSUE THREAD

**Issue by gbgelado** [predis/predis#682]
**Describe the bug**
I have an error warning and I haven't found anything about this type of problem. Can someone please give me a light?

```
Predis\ClientException\Jobs\SaveOrders
Command 'OFFSETGET' is not a registered Redis command.
```

**To Reproduce**
I have a command in Laravel that exports data from one database (treated) to another bank that is used for reporting. This happens in a queue, so it goes through Redis.

I noticed that these errors happen only when the FPM processes use more CPU resources.

**Versions (please complete the following information):**
 - Laravel: 6.20.7
 - Predis: 1.1
 - PHP 7.4.12
 - Redis Server [Redis server v=6.0.9 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=3012f034cc61d5f3]
 - OS 20.04

The code:
```php
$commandID = strtoupper($commandID);

if (!isset($this->commands[$commandID])) {
    throw new ClientException("Command '$commandID' is not a registered Redis command.");
}

$commandClass = $this->commands[$commandID];
```

Sorry for not having more information, but this appears in the error log and I did not find anything researching on the subject.

**Comment by przemyslaw-lapinski** [comment]
+1

**Comment by mmlsx** [comment]
+1

**Comment by abdiazizfarah** [comment]
Hey @gbgelado, any update on this issue?

**Comment by jeremyrodeo** [comment]
Why is this closed? Did someone find a way to solve it?

**Comment by tillkruss** [comment]
@jeremyrodeo: Feel free to open a PR.

**Comment by duyanh1904** [comment]
I have same problem with it when excute very large number queue, can new version predis resolve it?

**Comment by tillkruss** [comment]
`OFFSETGET` is not a Redis command, this is an issue with Laravel or one of its packages. A full call stack would revel the cause.
