### ISSUE TITLE
Decent Documentation

### ISSUE THREAD

**Issue by pluc** [predis/predis#689]
I'm trying to figure out the return values of various operations (get, publish) but there is no documentation that includes this information, and the source is such that I can't find the relevant methods.

**Describe the solution you'd like**
I'd like standard documentation that says what each method returns, its type and what it stands for.

**Describe alternatives you've considered**
Looking at the source, looking at [whatever this is](https://squizzle.me/php/predis/doc/Classes)

**Comment by tillkruss** [comment]
If your IDE doesn't show you method comments, you're welcome to contribute your feature request yourself here: https://github.com/predis/docs

There even is a first PR with some structure: https://github.com/predis/docs/pull/1
