### ISSUE TITLE
Predis\ClientException No sentinel server available for autodiscovery.

### ISSUE THREAD

**Issue by balsanka** [predis/predis#698]
I want to use Predis with laravel 8 and tried to config  trough  'replication' => 'sentinel' config option.
But It's all doesn't work any configuration variants.Here is one example:

    'redis' => [

        'client'  => env('REDIS_CLIENT', 'predis'),
        'options' => [
            'replication' => 'sentinel',
            'service'     => 'mymaster',
            'parameters'  => [
                'password' => 'test',
                'port'=>'26379'
                'database' => 62,
            ],

        'default' => [
            'redis-1.dev',
            'redis-2.dev',
            'redis-3.dev',
         ]
]

**Comment by balsanka** [comment]
Seems like it doesn't support **sentinel** with **credentials** :( Any solutions?

**Comment by tillkruss** [comment]
Thanks for reporting this, @balsanka. Can you submit a PR with a solution?
