### ISSUE TITLE
Fatal error: Uncaught on AbstractConnection.php

### ISSUE THREAD

**Issue by alexolliveira** [predis/predis#702]
Help! I've tried starting Redis since May, but it always shows the same error.
**ERROR:**
Fatal error: Uncaught Predis\Connection\ConnectionException: No connection can be made because the target machine has actively rejected them. [tcp: //127.0.0.1: 6379] in vendor \predis\predis\src\Connection\AbstractConnection.php on line 155

**CODE:**
$client = new Predis\Client('tcp://127.0.0.1:6379');
$client->set('foo', 'bar');
$value = $client->get('foo');
echo $value;

**Comment by tillkruss** [comment]
```
No connection can be made because the target machine has actively rejected them.
```
