### ISSUE TITLE
Custom exceptions

### ISSUE THREAD

**Issue by IonutRealDevs** [predis/predis#707]
Hello, i have this code:
```
class MyClass {
  
  private $redis;

  function __construct() {
    $this->redis = new Predis\Client();

    try {
      $this->redis->connect();
    } catch(Predis\Connection\ConnectionException $e) {
      echo 'my error here';
    }
  }
}
```

Right now, this code shows this:
```
<b>Warning</b>: stream_socket_client(): unable to connect to tcp://127.0.0.1:6379
(No connection could be made because the target machine actively refused it.
) in <b>...\vendor\predis\predis\src\Connection\StreamConnection.php</b>
on line <b>127</b>my error here
```

Because of that warning from redis, my app crashes. I want to do something else in catch if the connection is not established. What i'm trying to do is to step over and get data directly from database if redis is not connected or it fails to connect, but in my app i receive that warning and the app crashes.

**Comment by tillkruss** [comment]
>No connection could be made because the target machine actively refused it.
