### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by hanweimin** [predis/predis#711]
my config option
Array
(
    [exceptions] => 1
    [prefix] => sjzj:
    [cluster] => redis
    [parameters] => Array
        (
            [database] => 0
            [password] => xxxxxxxxxxxxxxxxxx
        )
)

nodes option
Array
(
    [0] => tcp://10.103.16.12:6379
    [1] => tcp://10.103.0.10:6379
    [2] => tcp://10.103.12.11:6379
    [3] => tcp://10.103.6.12:6379
    [4] => tcp://10.103.12.90:6379
    [5] => tcp://10.103.100.156:6379
)

Note: The above configuration values have been modified, not the real values

6 external servers, three masters and three slaves

I tried to set 2000 data in a loop, the whole process was very long, resulting in php timeout

for ($i=0; $i<2000; $i++){
    $redis->set("a{$i}", $i)
}

Maximum execution time of 30 seconds exceeded

I really don’t know what to do, please give pointers, thanks!!!

redis 6.2.5
php 7.4.3
centos7.9

**Comment by tillkruss** [comment]
Try setting a timeout of 5s and see if you get an error instead.

**Comment by hanweimin** [comment]
> Try setting a timeout of 5s and see if you get an error instead.

When I try to get 1000 pieces of data from 2000 pieces of data, the whole process will take about 25 seconds, which is too slow

**Comment by tillkruss** [comment]
Ah, then you must increase your PHP timeouts.

**Comment by hanweimin** [comment]
> Ah, then you must increase your PHP timeouts.

What I mean is that it will take such a long time to pass for set or get 1000 pieces of data. This is an abnormal phenomenon; it is not a question of whether to modify the PHP execution time.

If I change to a single point of redis, for set or get 1000 data, the process can be completed in an instant

**Comment by tillkruss** [comment]
You could try using Blackfire to analyze whether Predis is slow or your Redis Cluster response.
