### ISSUE TITLE
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by tcagkansokmen** [predis/predis#714]
Suddenly I started to get that error, 

stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/predis/predis/src/Connection/StreamConnection.php:246

Whats wrong with It?
I can connect to project from my local. But not working at my server

**Comment by tillkruss** [comment]
Are you using PHP 8.1?

**Comment by tillkruss** [comment]
Fixed in #743.

**Comment by odahcam** [comment]
Isn't this fix available for PHP 8.0?
