### ISSUE TITLE
Error while reading line from the server. Again

### ISSUE THREAD

**Issue by fedorovmixail** [predis/predis#715]
Hello!
I saw this (https://github.com/predis/predis/issues/33) very similar issue, but such method doesn't work.

For example, this code throw such error -> ```Fatal error: Uncaught Predis\Connection\ConnectionException: Error while reading line from the server. ```
```
    $read_client = new Client([
      'scheme'   => 'tcp',
      'host'     => 'host.org',
      'port'     => '6379',
      'database' => '1',
      'password' => 'pass',
      'timeout'  => 10,
      'read_write_timeout'  => -1,
    ]);

    $read_client->set('library', 'predis');

    $data = $read_client->get('library');
    sleep(3);
    $data2 = $read_client->get('library');
```

I set ``` 'read_write_timeout'  => -1 ```, but it doesn't work.

=========================================================

I think the reason in this place ```\Predis\Connection\StreamConnection::assertParameters()```

**Comment by jackbaron** [comment]
Please reopen issue i got a same prolem
