### ISSUE TITLE
Gracefully handle Redis failovers

### ISSUE THREAD

**Issue by matthewswain** [predis/predis#720]
**Is your feature request related to a problem? Please describe.**

I run an AWS ElastiCache Redis instance with multi-AZ enabled, i.e. a read/write primary node with a read-only replica (and auto fail over enabled). When failing over, long running processes retain their open connections to what was the primary node, but since it is now the read-only replica this results in many instances of `Predis\Response\ServerException` with messages containing `READONLY You can't write against a read only replica`. As the process catches these exceptions, these errors continue until the process is restarted.

**Describe the solution you'd like**

I would like to add some logic to Client->onErrorResponse to inspect the response and when experiencing this error, close/reopen the connection before throwing, as in this case I would consider the connection to be in a "known bad state" and so it should not be reused in subsequent calls. Reopening the connection should result in a connection to the new primary and so subsequent calls will succeed, facilitating fail over.

**Describe alternatives you've considered**

It is possible to catch this type of error in the application using predis, but in my case the application is a third party application, and also I feel that it makes sense for predis to handle this. (I believe phpredis does.)

**Additional context**

I would be happy to look at making this change, but I wanted to open this issue to confirm if it is likely to be accepted.

**Comment by tillkruss** [comment]
That sounds good. Can you target the v2.0 branch?

**Comment by frutality** [comment]
I would gladly help with testing this feature.

@matthewswain by any chance do you mean Laravel Horizon by third party application?
