### ISSUE TITLE
ERR wrong number of arguments for 'mget' command {"exception":{}}

### ISSUE THREAD

**Issue by webspecialist221** [predis/predis#721]
**Describe the bug**
i am trying to run the laravel project where i got this issue. I tries too much to solve this. i am stuck here since from 1 NOVEMBER. 2020. i need help in this issue. i don't know that it's predis issue or what.

**Comment by tillkruss** [comment]
Hi! You're not using `MGET` correctly. It's not an issue with Predis.

```
wrong number of arguments for 'mget' command
```
