### ISSUE TITLE
1 test failure with PHP 8.1

### ISSUE THREAD

**Issue by remicollet** [predis/predis#733]
```
There was 1 failure:

1) Predis\Command\StringSetRangeTest::testHandlesBinaryData
Failed asserting that 2147483648 matches expected -2147483648.

/builddir/build/BUILD/predis-a2fb02d738bedadcffdbb07efa3a5e7bd57f8d6e/tests/Predis/Command/StringSetRangeTest.php:98

```

**Comment by tillkruss** [comment]
Calling in the big guns @michael-grunder.

See this test case:

https://github.com/predis/predis/blob/4c1aada5aebf0afde266b512ed069f822148c3a2/tests/Predis/Command/Redis/SETRANGE_Test.php#L94-L102

I'm getting different results for `unpack('i', pack('i', -2147483648))` on varying architectures:
- x86: `-2147483648`
- arm: `2147483648`

**Comment by tillkruss** [comment]
@remicollet: If this a blocker for you right now, I just remove the test for now.

**Comment by michael-grunder** [comment]
I only quickly checked but I'm different behavior in `pack()` and `unpack()` in PHP 8.1.x (vs older versions of PHP).

```php
<?php
$val = -2147483648;
$packed = pack('i', $val);
$unpacked = unpack('i', $packed)[1];

echo phpversion() . " => $val => $unpacked\n";
```

Linux x86_64
```bash
$ uname -a Linux cthulhu 5.11.0-41-generic #45-Ubuntu SMP Fri Nov 5 11:37:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ php7.4 /tmp/packunpack.php
7.4.26 => -2147483648 => -2147483648
$ php8.0 /tmp/packunpack.php
8.0.14 => -2147483648 => -2147483648
$ php8.1 /tmp/packunpack.php
8.1.1 => -2147483648 => 2147483648
```

Darwin aarch64:
```bash
❯ uname -a
Darwin Michaels-Mac-mini.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
❯ /opt/homebrew/opt/php@7.4/bin/php /tmp/packunpack.php
7.4.27 => -2147483648 => -2147483648
❯ /opt/homebrew/opt/php@8.0/bin/php /tmp/packunpack.php
8.0.14 => -2147483648 => -2147483648
❯ /opt/homebrew/opt/php@8.1/bin/php /tmp/packunpack.php
8.1.1 => -2147483648 => 2147483648
```

**Comment by remicollet** [comment]
> @remicollet: If this a blocker for you right now, I just remove the test for now.

Not a blocker (I simply exclude this test for now)

**Comment by remicollet** [comment]
For me it looks like a regression as -2147483648 is a valid 32-bit signed int.

https://github.com/php/php-src/issues/7899

**Comment by michael-grunder** [comment]
@remicollet Thanks for looking into it (and for fixing it in PHP!).  :heart:
