### ISSUE TITLE
ClientInterface::get() is supposed to return string but actually can return \Predis\Response\Status

### ISSUE THREAD

**Issue by repli2dev** [predis/predis#734]
**Describe the bug**
The ClientInterface::get() has documented `string` as return type, but on some situations (detected in production) it may return `\Predis\Response\Status`.

**To Reproduce**
Steps to reproduce the behavior: unknown

**Expected behavior**
Either only string is returned or the current state is properly documented.

**Versions (please complete the following information):**
 - Predis: 1.1.9
 - PHP 7.4
 - Redis Server 6.2.6
 - OS Docker redis:latest

**Additional context**
Libraries such as contributte/redis depends on the string type and handle it in such way that `Status` object create an `TypeError` ([issue](https://github.com/contributte/redis/issues/34) reported, but fix here is probably also needed).

**Comment by repli2dev** [comment]
@tillkruss PR created: https://github.com/predis/predis/pull/735/files

The casting is not plausible as it returns the Status response as the content of the key, which will certainly break things... just a bit later.

**Comment by repli2dev** [comment]
Any comments for the proposed change?

**Comment by tillkruss** [comment]
Closing until this can be replicated.
