### ISSUE TITLE
MODULE command is not supported

### ISSUE THREAD

**Issue by abdennor** [predis/predis#738]
I'm trying to use Predis with RedisJson and the lib execute  MODULE command to check for json module support, but Predis can't excute it, it's unknown for it 'ERR unknown command 'MODULE''
any suggestions please ?

**Comment by tillkruss** [comment]
There is no high level support currently, you can use `RawCommand` tho.

**Comment by abdennor** [comment]
it seems that Command is not allowed in Redis Enterprise cloud instance 
check this bro [what redis say's](https://stackoverflow.com/questions/70719895/init-redisjson-with-predis-module-version-error?noredirect=1#comment125031551_70719895)
