### ISSUE TITLE
Transaction not locking the key way expected

### ISSUE THREAD

**Issue by sagarsolace** [predis/predis#741]
**Code sample**
$redis->transaction()->set('lastTokenNumber', (string)($lastTokenNumber+1))->get('lastTokenNumber')->execute();

**Additional context**
You can see above command should lock the key lastTokenNumber while other concurrent requests are executing over the server.
But its not plese refer the jmeter stress test response we are getting.

Please help to know what exact thing we are missing here.

![image](https://user-images.githubusercontent.com/41356420/151588900-ed47efda-a949-4097-9ae0-e8c7b228b012.png)

![image](https://user-images.githubusercontent.com/41356420/151588959-023666be-2c0f-4171-89ff-b5b9ff1b6cd6.png)

**Comment by tillkruss** [comment]
Can you open a PR with a fix?

**Comment by jotaszewsky** [comment]
If I understand correctly. 
I think this is not a bug and redis by default does not lock the key between different clients. You should use the `watch` function to solve your problem. Usage example:

```
$transaction = $redis->transaction()
$transaction->watch('lastTokenNumber');
transaction->set('lastTokenNumber', (string)($lastTokenNumber+1))->get('lastTokenNumber')->execute();
```

Now `execute()` throws an exception if the key `lastTokenNumber` was changed after watch.
You can find more information about this mechanism directly in the redis documentation
[https://redis.io/topics/transactions#optimistic-locking-using-check-and-set](https://redis.io/topics/transactions#optimistic-locking-using-check-and-set)
