### ISSUE TITLE
How to write hierarchical structure of data ?

### ISSUE THREAD

**Issue by sergeynilov** [predis/predis#751]
Hello,
If there is a way in laravel 9 / "predis/predis": "^1.1" app with redis v 5.0.7 to write
hierarchical structure of data and later to read it? If yes please, link to example.

Thanks!

**Comment by tillkruss** [comment]
`serialize()`

**Comment by sergeynilov** [comment]
Sorry, if I put my question in poor way. I mean how to write hierarchical structure on redis side ? Like ItemRoot and ItemSubRoot1, ItemSubRoot2...
