### ISSUE TITLE
predis incompatible with Sentinel in Redis 7

### ISSUE THREAD

**Issue by rhl-jfm** [predis/predis#754]
In a Redis Sentinel cluster, predis still uses the SENTINEL SLAVES command to find replicas. This command was deprecated in Redis 6 (replaced by SENTINEL REPLICAS command). The SENTINEL SLAVES command was removed entirely in Redis 7.

In order to work with Redis 7+ Sentinel clusters, predis should be updated to use the SENTINEL REPLICAS command instead.

**Comment by tillkruss** [comment]
Right on. Can you submit a PR with a possible solution?

**Comment by tillkruss** [comment]
https://github.com/redis/redis/pull/10723
