### ISSUE TITLE
Return type in method "setex" specified as "int", but actually returns "Predis\Response\Status" instance

### ISSUE THREAD

**Issue by bolatovdarkhan25** [predis/predis#757]
**Describe the bug**

**To Reproduce**
1. $client = new Predis\Client(['host' => 'blabla', 'port': 6379]);
    $response = $client->setex('key', 86400, 'val');
2. returned Predis\Response\Status^ {#373  -payload: "OK"}

**Expected behavior**
Expected that response type will be "int", but get "Predis\Response\Status"

**Versions:**
 - Predis: 1.1.10
 - PHP: 8.1
 - OS: Ubuntu 20.04

**Code sample**
$client = new Predis\Client(['host' => 'blabla', 'port': 6379]);
$response = $client->setex('key', 86400, 'val');
![image](https://user-images.githubusercontent.com/48150435/166408660-e615db66-b3a5-4a7d-8fdd-3e20aa93ae57.png)
![image](https://user-images.githubusercontent.com/48150435/166408677-5506e1e5-95df-4533-ad90-fa02996d0d18.png)

**Comment by tillkruss** [comment]
Can you submit a PR with a fix?
