### ISSUE TITLE
Multiple sentinels, which one will be connected

### ISSUE THREAD

**Issue by DylanBack** [predis/predis#763]
I have configured multiple sentinel ips. 
$sentinels = ['tcp://10.0.0.1', 'tcp://10.0.0.2', 'tcp://10.0.0.3'];

Does each connection connect to the first one, or will one randomly be selected?

**Comment by zaherg** [comment]
which version do you use? `v1.1` or `main`?

**Comment by tillkruss** [comment]
Not sure, check your Redis logs.
