### ISSUE TITLE
ERR unknown subcommand 'SLAVES'. Try SENTINEL HELP.

### ISSUE THREAD

**Issue by aurril** [predis/predis#775]
**Describe the bug**
When using Sentinel Replication with Redis 7.0 the following error message is sporadically returned:
ERR unknown subcommand 'SLAVES'. Try SENTINEL HELP.

**Expected behavior**
No error and successful connection to Redis.

**Versions (please complete the following information):**
 - Predis: 2.0.0
 - PHP 7.2.24
 - Redis Server 7.0.0
 - OS Ubuntu 20.04 LTS

**Additional context**
The error is triggered, when the client tries to query sentinel for available slaves. In Redis 7.0 the SENTINEL SLAVES command was removed in favour of SENTINEL REPLICAS.

**Comment by tillkruss** [comment]
Upgrade to 7.0.1.
