### ISSUE TITLE
Cannot Connect To Redis Using Non-Default User

### ISSUE THREAD

**Issue by raviMukti** [predis/predis#778]
i can't connect to redis using a non-default user

i followed the instructions to use **username** based on the release notes for version 1.1.4 [here](https://github.com/predis/predis/releases/tag/v1.1.4)

below is my example code
```
return new Predis\Client([
            "scheme" => $settings["scheme"], //tcp
            "host" => $settings["host"],
            "port" => $settings["port"],
            "username" => $settings["user"], //non-default user
            "database" => $settings["instance"],
            "password" => $settings["password"]
        ]);
```
but it always gives me error
```
Predis\Connection\ConnectionException: `AUTH` failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? [tcp://127.0.0.1:6379]
```

did i do it wrong?

**Versions Specification:**
 - Predis: 1.1.10
 - PHP : 7.4
 - Redis Server : 7.0.2
 - OS Ubuntu 22.04

**Comment by tillkruss** [comment]
>ERR AUTH <password> called without any password configured for the default user.
