### ISSUE TITLE
Class already in use bug when a Symfony bundle is requiring Predis

### ISSUE THREAD

**Issue by alex205** [predis/predis#790]
**Describe the bug**
I am creating a Symfony bundle which uses Predis to access to Redis cache. The bundle have Predis in its composer dependencies. When I import my bundle in a Symfony project using composer with local repository, I got the following error: "Compile Error: Cannot declare class Predis\Connection\Factory, because the name is already in use". Predis version is 2.0.0.

I've tried back restricting Predis version to ^1.1, the error is no longer displayed. It seems that there is a changed between the two versions causing the error.

**To Reproduce**
1. Create a Symfony bundle (called `acme/bundle`) and then require `snc/redis-bundle` and `predis/predis`
2. Create a Symfony project which requires `acme/bundle`
3. See error "Compile Error: Cannot declare class Predis\Connection\Factory, because the name is already in use"
4. Downgrade the Predis version to ^1.1 in `acme/bundle`
5. Error has disappeared

**Expected behavior**
I expect to have the same behaviour between version 2.0.0 and ^1.1.

**Versions (please complete the following information):**
 - Predis: [2.0.0 then 1.1.10]
 - Snc Redis: [4.2.1]
 - PHP [8.1.8]
 - Redis Server [6.0.9]
 - OS [Debian 11.3]

**Comment by tillkruss** [comment]
Please post the full stack trace.
