### ISSUE TITLE
supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by lechatthecat** [predis/predis#793]
**Describe the bug**
predis/predis/src/Connection/StreamConnection.php:291 is throwing an exception.
Except this, predis seems to be working as expected.
```
fwrite(): supplied resource is not a valid stream resource {"exception":"[object] (TypeError(code: 0): fwrite(): supplied resource is not a valid stream resource at /predis/predis/src/Connection/StreamConnection.php:291)
```

**To Reproduce**
Use predis with PHP 8.1.6

**Expected behavior**
It should not throw exception even if the resource is already closed.

**Versions (please complete the following information):**
 - Predis: 1.1.9
 - PHP 8.1.6

**Additional context**
I think it is throwing an exception because the fwrite behavior was changed in PHP8.
https://github.com/php/doc-en/issues/1581

**Comment by tillkruss** [comment]
Can you open a PR with a fix, as well as a test that triggers this exception?

**Comment by stebogit** [comment]
Hello, I'm having the same issue and my logs are filling up quite quickly...
Same versions, using Horizon in a Laravel app running on Heroku and using a Redis Cloud instance

**Comment by tillkruss** [comment]
@stebogit: Please open a PR.

**Comment by stebogit** [comment]
Looks like this is going to happen also on v2, indeed due to PHP8 updates: https://onlinephp.io/c/d9f12

**Comment by streamingsystems** [comment]
Hi all,

I just opened ticket [https://github.com/predis/predis/issues/801]801. Were you seeing this as well? They seem related but yours is for write and our issue is for read.

**Comment by lechatthecat** [comment]
@stebogit 
Thank you very much for your fix, but I have one question.
[Here](https://github.com/predis/predis/pull/799/files#diff-04e6f9fb63cbb6f3aa0cedda5fc36995b503c5ca90133336843525eb2104c28aR292), when resource is not a valid resource, you are assigning `false`, but shouldn't it be `null` because closed resource is null? If you false is assigned here, I think it will throw another exception [here](https://github.com/predis/predis/pull/799/files#diff-04e6f9fb63cbb6f3aa0cedda5fc36995b503c5ca90133336843525eb2104c28aR298).

@tillkruss 
Thank you very much for your maintenance, too. Please let me ask, is this fix included in v1.1? I cannot find v1.1 that contains this fix.
https://github.com/predis/predis/pull/799#issuecomment-1251451961

**Comment by stebogit** [comment]
@lechatthecat I believe line 299 won't get executed if `$write` is `false`

**Comment by lechatthecat** [comment]
@stebogit 
But the condition of the exception is :
```
if ($written === false || $written === 0) {
```
so why not?

**Comment by stebogit** [comment]
@lechatthecat an invalid resource passed to `@fwrite()` returned ` in PHP <=7.x, while in PHP 8 it throws a `TypeError`. Tha was the fix introduced by my PR.
I believe the exception thrown is then handled properly by the library, while an unexpected error just breaks the scripts

**Comment by lechatthecat** [comment]
@stebogit 
I see, I think other part is right. Thank you for your fix 👍

**Comment by lechatthecat** [comment]
But maybe it's better if someone change it to `null`?
