### ISSUE TITLE
Question: Does PRedis support RESP3?

### ISSUE THREAD

**Issue by RohanNagar** [predis/predis#795]
Hi, I had a quick question for the maintainers. Does PRedis have support for the RESP3 protocol or does it still only use RESP2?

If it has support for RESP3, is there a configuration option that can be used to set the desired protocol version to either 2 or 3?

Thank you!

**Comment by tillkruss** [comment]
Using RESP2. Is there any v3 feature you're looking for?

**Comment by RohanNagar** [comment]
Thanks! No feature in particular, just wanted to see what was used under the hood.

**Comment by tillkruss** [comment]
Cool. PhpRedis and [Relay](https://relay.so) use hiredis as their underlying clients and they both do full RESP3.
