### ISSUE TITLE
Script attempted to access nonexistent global variable

### ISSUE THREAD

**Issue by edwinsmasher** [predis/predis#798]
Am getting this error in the logs whenever i try to connect to the redis server in laravel 

@enable_strict_lua:15: user_script:7: Script attempted to access nonexistent global variable 'cjson' {"exception":"[object] (Predis\\Response\\ServerException(code: 0):

**Comment by tillkruss** [comment]
Likely related to your Lue script.

**Comment by mfn** [comment]
For the Redis queue transport, Laravel internally uses some LUA script using `cjson`; if you Redis server is restricted what LUA script it can executed, you need to fix that.

**Comment by edwinsmasher** [comment]
I reinstalled redis, Works great now.
