### ISSUE TITLE
fread(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by streamingsystems** [predis/predis#801]
We are running Laravel 9. 

We are using predis 1.1.10. It seems that for months (possibly starting when we upgraded to php 8) we have been randomly getting this a few times per day. We are unable to reproduce it at will. 

fread(): supplied resource is not a valid stream resource {"exception":"[object] (TypeError(code: 0): fread(): supplied resource is not a valid stream resource at .../vendor/predis/predis/src/Connection/StreamConnection.php:335)

The line in the code is (line 335): 

$chunk = fread($socket, min($bytesLeft, 4096));

I see that in version 2.0 that this line is still here, but on line 307:

$chunk = fread($socket, min($bytesLeft, 4096));
 
Does anyone know what would randomly cause this? It seems our redis server is running perfectly when this happens.

I did notice this recent fix in 2.0:

https://github.com/predis/predis/commit/7ad74217c2969418162f1dde0cfc1fe530e54f34

Where the code checks for a resource first before it does the write. 

I am wondering if that same concept can be applied to the read:

//$chunk = fread($socket, min($bytesLeft, 4096));  // old 
$chunk = is_resource($socket) ? fread($socket, min($bytesLeft, 4096)) : false; // new
 
I am going upgrade to predis 2.0 to be on the latest. However since the same line of code is there my guess it's going to behave the same way. 

Thanks!

-Rob

**Versions (please complete the following information):**
 - Predis: 1.1.10
 - PHP 8.1.10
 - Redis Server: 6.2.7
 - OS: Centos

**Comment by tillkruss** [comment]
Feel free to open a PR to v2 that adds the is-resource check to that fread as well.

**Comment by tillkruss** [comment]
Closed via #802.
