### ISSUE TITLE
 Predis v2.0.x with Redis Sentinels - No sentinel server available for autodiscovery

### ISSUE THREAD

**Issue by wuyuhang18325533531** [predis/predis#806]
**Describe the bug**

**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**

**Versions (please complete the following information):**
 - Predis: [e.g. 1.1.2]
 - PHP [e.g. 8.0.0]
 - Redis Server [e.g. 6.0.0]
 - OS [e.g. Ubuntu 20.10]

**Code sample**
If applicable, a small snippet of code that reproduces the issue.

**Additional context**

**Comment by wuyuhang18325533531** [comment]
common issue with version 2.0,

It's a pity to use tls to connect to the sentinel, but unfortunately, it keeps reporting an error

```js
$sentinels = [
    [
        'scheme' => 'tls', 
        'ssl' => ['verify_peer' => false],
        'host' => "XXXXXXXX",
        'port' => 26379,
    ],
];
$options = [
    'sentinel_timeout' => 5.0,
    'update_sentinels' => true,
    'replication' => 'sentinel',
    'service'     => 'mymaster',
    'parameters'  => ['database' => 2, 'password' => 'XXXX'],
];

print_r($sentinels);
print_r($options);
$redis = new \Predis\Client($sentinels, $options);
```

**Comment by tillkruss** [comment]
Please properly report a bug or feature request and open a PR if you want it added.

**Comment by legreco** [comment]
does this issue has been solved. I have the same problem but with laravel
