### ISSUE TITLE
botman Framwork Redis Storage 

### ISSUE THREAD

**Issue by googleshokry** [predis/predis#809]
i  useded in botman Framwork Redis Storage 

1. when disconnected connect i have this error 

2. See error
[Wed Nov  2 12:48:49 2022] PHP Fatal error:  Uncaught ErrorException: fclose(): supplied resource is not a valid stream resource in /**/vendor/predis/predis/src/Connection/StreamConnection.php:247
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /**/vendor/predis/predis/src/Connection/StreamConnection.php(247): fclose()
#2 /**/vendor/predis/predis/src/Connection/StreamConnection.php(49): Predis\Connection\StreamConnection->disconnect()
#3 [internal function]: Predis\Connection\StreamConnection->__destruct()
#4 {main}
  thrown in /**/vendor/predis/predis/src/Connection/StreamConnection.php on line 247

[Wed Nov  2 12:48:49 2022] 127.0.0.1:34146 Closing

**Versions (please complete the following information):**
 - Predis: [2.0.3]
 - PHP [7.4]
 - Redis Server [6.0.6]
 - OS [e.g. Ubuntu 20.04]

**Comment by tillkruss** [comment]
Similar to #793 and #801.

@googleshokry: Can you open a PR with a fix?
