### ISSUE TITLE
src/Connection/StreamConnection.php

### ISSUE THREAD

**Issue by TimoFrenzel** [predis/predis#812]
Every now and then predis will here the error.

src/Connection/StreamConnection.php

```
ErrorException: Undefined variable $i in /var/www/htdocs/vendor/predis/predis/src/Connection/StreamConnection.php:357
```

**Comment by tillkruss** [comment]
Can you replicate it?

**Comment by tillkruss** [comment]
Can you open a PR with a fix?

**Comment by tillkruss** [comment]
I can't replicate it.

**Comment by aistis-** [comment]
Seems the issue still exists in latest version.
PHP 8.3
Predis 2.2.2
Redis 7.2.1

> Warning: Undefined variable $i
[src/Connection/StreamConnection.php:334](https://github.com/predis/predis/blob/1726db0f4761e8ddacfac574eb17a0f8d7bebe05/src/Connection/StreamConnection.php#L334)

Currently, I don't have a way to reproduce it. It happens occasionally on long-running process. After process restart issue does not occur for some time.

**Comment by andreashochhaltervisitrans** [comment]
We have the same issue, it spams our error logging and made it even crash.  I will test a patch with $i = 0; before the loop. Maybe it will avoid it.

<img width="2367" height="981" alt="Image" src="https://github.com/user-attachments/assets/a13db08e-7887-4d09-a202-19e3a69f4754" />

**Comment by tillkruss** [comment]
Feel free to open a PR to the `main` branch.
