### ISSUE TITLE
Add support for missing redis command ZDIFFSTORE

### ISSUE THREAD

**Issue by chayim** [predis/predis#816]
predis is missing support for some of the sorted set functions, such as [zdiffstore](https://redis.io/commands/zdiffstore/). This command has been available since Redis 6.2.0

**Comment by chayim** [comment]
@vladvildanov please!

**Comment by vladvildanov** [comment]
@chayim I assume it's a ZDIFFSTORE command, cause ZDIFFSCORE aren't exist, will change description
