### ISSUE TITLE
Fatal error: Uncaught Predis\Response\ServerException: ERR syntax error 

### ISSUE THREAD

**Issue by phpmooc** [predis/predis#832]
**Describe the bug**
`Fatal error: Uncaught Predis\Response\ServerException: ERR syntax error `

**To Reproduce**
I have read the issue related to #309, and do the same command like:
`$client->set('k1', '1', 'EX', '10', 'PX', '10000', 'NX');`, 
then run and throw errors as title described.

**Expected behavior**
Expect to work properly

**Versions (please complete the following information):**
 - Predis: [v2.0.1]
 - PHP [7.2 | 7.4 | 8.1]
 - Redis Server [5.0.3]
 - OS [CentOS 7.9]

**Code sample**
```
<?php
require dirname(__FILE__, 2) . "/vendor/autoload.php";

$redis = new \Predis\Client();
$redis->connect(); 
$redis->set('k1', '1', 'EX', '10', 'PX', '10000', 'NX');
```

**Comment by tillkruss** [comment]
```
SET k1 1 EX 10 PX 10000 NX
ERR syntax error
```

**Comment by phpmooc** [comment]
> ```
> SET k1 1 EX 10 PX 10000 NX
> ERR syntax error
> ```

I feel puzzled why u closed this issue, so what's the problem for the code：
```
$redis->set('k1', '1', 'EX', '10', 'PX', '10000', 'NX');
``` 
and I couldn't understand the connection between the code you gave me and the code I described.  tks so much

**Comment by phpmooc** [comment]
to put it simply，I just wanna know what is the proper way to use `set` comand in predis with those extend options like `EX`、`PX` or `NX` and so on.
