### ISSUE TITLE
Add support for missing redis command CREATECONSUMER

### ISSUE THREAD

**Issue by chayim** [predis/predis#846]
predis currently lacks support for the function [CREATECONSUMER](https://redis.io/commands/CREATECONSUMER)

**Comment by vladvildanov** [comment]
@chayim Is this command exist? Link is broken and I can't find this command at docs

**Comment by tillkruss** [comment]
Maybe he means this? https://redis.io/commands/xgroup-createconsumer/

**Comment by vladvildanov** [comment]
@tillkruss I guess you're right

**Comment by vladvildanov** [comment]
@tillkruss @chayim  Just find out that there's separate issue for XGROUP-CREATECONSUMER. So question is still open, do we need this issue?

#856

**Comment by chayim** [comment]
Closing. I'm bad at generating things sometimes. Sorry about this!
