### ISSUE TITLE
Add support for missing redis command XAUTOCLAIM

### ISSUE THREAD

**Issue by chayim** [predis/predis#855]
predis currently lacks support for the function [XAUTOCLAIM](https://redis.io/commands/XAUTOCLAIM)

**Comment by vladvildanov** [comment]
@chayim We haven't support for base stream commands to work with consumers and groups. I think it worse to add it before, so we can perform a proper testing on it

**Comment by chayim** [comment]
Sounds like a bunch of issues to create :D

**Comment by vladvildanov** [comment]
@chayim Exactly 😎
