### ISSUE TITLE
Call LUA Script with array

### ISSUE THREAD

**Issue by brassel** [predis/predis#88]
Can I give an array as an ARGV argument to a lua script? Maybe I am doing something wrong but I always get a warning followed by an error like this:

PHP Warning:  strlen() expects parameter 1 to be string, array given in /Users/doc/Sites/redis-php/predis/lib/Predis/Connection/StreamConnection.php on line 285

PHP Fatal error:  Uncaught exception 'Predis\ServerException' with message 'ERR Protocol error: invalid bulk length'

Is there something I could do about this?

Thanks for your time and your great work!

**Comment by malkusch** [comment]
I have currently the same issue and solve it with `call_user_func_array`. HTH:

    return call_user_func_array(
        [$client, "eval"],
        array_merge([$script, $numkeys], $arguments)
    );
