### ISSUE TITLE
Support new Redis 6.2 arguments for ACL GETUSER

### ISSUE THREAD

**Issue by chayim** [predis/predis#975]
Add support for the enw arguments in Redis 6.2 for ACL GETUSER as specified at https://redis.io/commands/ACL-GETUSER.

Detail of update: Added selectors and changed the format of key and channel patterns from a list to their rule representation.

This is part of #820.
Note: Due to the autogenerated nature of this, some of this may be already implemented.

**Comment by vladvildanov** [comment]
Closed #1193
