### ISSUE TITLE
KEYS returns keys incl. prefix

### ISSUE THREAD

**Issue by korpa** [predis/predis#98]
When searching for keys through a prefix enabled connection, KEYS returns all keys including the prefix. So before using a GET on these keys you have to remove the prefix from the key manually (e.g. str_replace).

**Comment by jafrim** [comment]
`$client = new ExampleClient('tcp://127.0.0.1', array('prefix' => 'pfx:'));
$client->mset('foo', 'bar', 'hoge', 'piyo');
$keys = $client->keys('*');
var_dump($keys);`
