### ISSUE TITLE
Support new Redis 6.2 arguments for CONFIG GET

### ISSUE THREAD

**Issue by chayim** [predis/predis#981]
Add support for the enw arguments in Redis 6.2 for CONFIG GET as specified at https://redis.io/commands/CONFIG-GET.

Detail of update: Added the ability to pass multiple pattern parameters in one call

This is part of #820.
Note: Due to the autogenerated nature of this, some of this may be already implemented.

**Comment by vladvildanov** [comment]
Closed as already supported
