### ISSUE TITLE
Support new Redis 6.2 arguments for CONFIG SET

### ISSUE THREAD

**Issue by chayim** [predis/predis#982]
Add support for the enw arguments in Redis 6.2 for CONFIG SET as specified at https://redis.io/commands/CONFIG-SET.

Detail of update: Added the ability to set multiple parameters in one call.

This is part of #820.
Note: Due to the autogenerated nature of this, some of this may be already implemented.

**Comment by vladvildanov** [comment]
Closed as already supported
