### ISSUE TITLE
Support new Redis 6.2 arguments for GEORADIUSBYMEMBER

### ISSUE THREAD

**Issue by chayim** [predis/predis#986]
Add support for the enw arguments in Redis 6.2 for GEORADIUSBYMEMBER as specified at https://redis.io/commands/GEORADIUSBYMEMBER.

Detail of update: Added support for uppercase unit names.

This is part of #820.
Note: Due to the autogenerated nature of this, some of this may be already implemented.

**Comment by vladvildanov** [comment]
Closed as not needed, functionality already covered
